import { MongoClient } from "mongodb";
import { getUsersCollection, getToolsCollection } from "./db";
import { createTool } from "./models/Tool";
import { createUser } from "./models/User";
const bcrypt = require("bcryptjs");

const initialTools = [
  // Chat & Language Models
  {
    name: "ChatGPT",
    description:
      "Advanced AI language model for conversation, writing, and content creation",
    url: "https://chat.openai.com",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Chat", "Writing", "OpenAI", "GPT-4"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    color: "#10a37f",
    pros: [
      "Powerful language model",
      "Great for writing",
      "Easy to use",
      "Regular updates",
    ],
    cons: ["Can be expensive", "Sometimes inaccurate", "Limited context"],
    features: [
      "Text generation",
      "Code assistance",
      "Translation",
      "Creative writing",
    ],
    status: "active" as const,
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
    apiAvailable: true,
    apiUrl: "https://platform.openai.com/docs/api-reference",
  },
  {
    name: "Claude",
    description:
      "Anthropic's AI assistant for writing, analysis, and creative tasks",
    url: "https://claude.ai",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Writing", "Analysis", "Anthropic", "Claude"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/86/Anthropic_logo.svg",
    color: "#d97706",
    pros: ["Excellent writing", "Good reasoning", "Safe AI", "File uploads"],
    cons: ["Limited availability", "No mobile app", "Subscription required"],
    features: [
      "Text analysis",
      "File processing",
      "Creative writing",
      "Code assistance",
    ],
    status: "active" as const,
    website: "https://anthropic.com",
    documentation: "https://docs.anthropic.com",
  },
  {
    name: "Bard",
    description:
      "Google's AI chatbot for creative collaboration and information",
    url: "https://bard.google.com",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Chat", "Google", "Creative", "Information"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg",
    color: "#4285f4",
    pros: [
      "Free to use",
      "Real-time information",
      "Multimodal",
      "Google integration",
    ],
    cons: ["Limited availability", "Sometimes inaccurate", "Privacy concerns"],
    features: [
      "Text generation",
      "Image analysis",
      "Web search",
      "Creative writing",
    ],
    status: "active" as const,
    website: "https://bard.google.com",
    documentation: "https://bard.google.com/faq",
  },
  {
    name: "Perplexity AI",
    description:
      "AI-powered search engine that provides accurate answers with sources",
    url: "https://perplexity.ai",
    category: "ai-chat",
    subcategory: "Search & Research",
    tags: ["AI", "Search", "Research", "Sources", "Accuracy"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://assets.perplexity.ai/logo192.png", // Updated to real logo
    color: "#6366f1",
    pros: [
      "Accurate answers",
      "Source citations",
      "Real-time search",
      "Free tier",
    ],
    cons: [
      "Limited features in free version",
      "Sometimes slow",
      "Limited context",
    ],
    features: [
      "Web search",
      "Source citations",
      "Multiple perspectives",
      "Real-time data",
    ],
    status: "active" as const,
    website: "https://perplexity.ai",
    documentation: "https://docs.perplexity.ai",
  },

  // Image Generation
  {
    name: "Midjourney",
    description:
      "AI-powered image generation tool for creating stunning artwork and designs",
    url: "https://midjourney.com",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Art", "Design", "Creative"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Midjourney_logo.svg/1200px-Midjourney_logo.svg.png",
    color: "#8b5cf6",
    pros: [
      "High-quality images",
      "Creative control",
      "Fast generation",
      "Artistic style",
    ],
    cons: ["Paid service", "Discord-based", "Limited free tier"],
    features: [
      "Image generation",
      "Style variations",
      "Upscaling",
      "Custom prompts",
    ],
    status: "active" as const,
    website: "https://midjourney.com",
    documentation: "https://docs.midjourney.com",
  },
  {
    name: "DALL-E",
    description:
      "OpenAI's AI system for creating realistic images from text descriptions",
    url: "https://openai.com/dall-e-2",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "OpenAI", "Text-to-Image", "Creative"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg",
    color: "#10a37f",
    pros: [
      "High quality",
      "Easy to use",
      "Good editing tools",
      "API available",
    ],
    cons: ["Expensive", "Limited free credits", "Content restrictions"],
    features: ["Text-to-image", "Image editing", "Variations", "Outpainting"],
    status: "active" as const,
    website: "https://openai.com/dall-e-2",
    documentation: "https://platform.openai.com/docs/guides/images",
    apiAvailable: true,
    apiUrl: "https://platform.openai.com/docs/api-reference/images",
  },
  {
    name: "Stable Diffusion",
    description:
      "Open-source AI image generation model for creating art and designs",
    url: "https://stability.ai",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Open Source", "Art", "Local"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Stable_Diffusion_logo.svg/1200px-Stable_Diffusion_logo.svg.png",
    color: "#059669",
    pros: [
      "Open source",
      "Local deployment",
      "Customizable",
      "No usage limits",
    ],
    cons: ["Technical setup", "Hardware requirements", "Quality varies"],
    features: [
      "Image generation",
      "Style transfer",
      "Inpainting",
      "Custom models",
    ],
    status: "active" as const,
    website: "https://stability.ai",
    documentation: "https://github.com/CompVis/stable-diffusion",
    apiAvailable: true,
    apiUrl: "https://platform.stability.ai",
  },
  {
    name: "Canva AI",
    description:
      "AI-powered design tool for creating professional graphics and presentations",
    url: "https://canva.com",
    category: "ai-image",
    subcategory: "Design Tools",
    tags: ["AI", "Design", "Graphics", "Templates", "Collaboration"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg",
    color: "#00c4cc",
    pros: ["Easy to use", "Templates", "Collaboration", "AI features"],
    cons: ["Limited free features", "Watermarks", "Internet required"],
    features: [
      "AI image generation",
      "Templates",
      "Collaboration",
      "Brand kit",
    ],
    status: "active" as const,
    website: "https://canva.com",
    documentation: "https://www.canva.com/help/",
  },

  // Video Generation
  {
    name: "Runway ML",
    description: "AI video generation and editing platform for creators",
    url: "https://runwayml.com",
    category: "ai-video",
    subcategory: "Video Generation",
    tags: ["AI", "Video", "Editing", "Creative", "Film"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://runwayml.com/_next/static/media/logo.2b7e2e7e.svg", // Updated to real logo
    color: "#7c3aed",
    pros: [
      "Professional quality",
      "Multiple tools",
      "Easy interface",
      "Regular updates",
    ],
    cons: ["Expensive", "Learning curve", "Limited free tier"],
    features: [
      "Video generation",
      "Object removal",
      "Motion tracking",
      "Green screen",
    ],
    status: "active" as const,
    website: "https://runwayml.com",
    documentation: "https://runwayml.com/docs",
  },
  {
    name: "Synthesia",
    description:
      "AI video generation platform for creating talking head videos",
    url: "https://synthesia.io",
    category: "ai-video",
    subcategory: "Video Generation",
    tags: ["AI", "Video", "Avatars", "Training", "Business"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://uploads-ssl.webflow.com/5f6b8b7b8b7b8b7b8b7b8b7b/5f6b8b7b8b7b8b7b8b7b8b7b_synthesia-logo.svg", // Updated to real logo
    color: "#dc2626",
    pros: [
      "Professional avatars",
      "Easy to use",
      "Multiple languages",
      "Custom avatars",
    ],
    cons: ["Expensive", "Limited customization", "Subscription required"],
    features: [
      "AI avatars",
      "Text-to-speech",
      "Multiple languages",
      "Custom branding",
    ],
    status: "active" as const,
    website: "https://synthesia.io",
    documentation: "https://help.synthesia.io",
  },
  {
    name: "Pika Labs",
    description:
      "AI-powered video generation tool for creating short videos from text",
    url: "https://pika.art",
    category: "ai-video",
    subcategory: "Video Generation",
    tags: ["AI", "Video", "Text-to-Video", "Creative", "Short-form"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Pika_Labs_logo.svg/1200px-Pika_Labs_logo.svg.png",
    color: "#f59e0b",
    pros: ["Easy to use", "Fast generation", "Good quality", "Free tier"],
    cons: ["Limited duration", "Watermarks", "Limited customization"],
    features: [
      "Text-to-video",
      "Image-to-video",
      "Style transfer",
      "Video editing",
    ],
    status: "active" as const,
    website: "https://pika.art",
    documentation: "https://pika.art/docs",
  },

  // Code & Development
  {
    name: "GitHub Copilot",
    description: "AI-powered code completion and pair programming assistant",
    url: "https://github.com/features/copilot",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "Development", "GitHub", "IDE"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg",
    color: "#24292e",
    pros: [
      "Excellent code completion",
      "IDE integration",
      "Multi-language support",
      "Context aware",
    ],
    cons: [
      "Subscription required",
      "Sometimes suggests wrong code",
      "Privacy concerns",
    ],
    features: [
      "Code completion",
      "Function generation",
      "Documentation",
      "Test generation",
    ],
    status: "active" as const,
    website: "https://github.com",
    documentation: "https://docs.github.com/en/copilot",
  },
  {
    name: "Cursor",
    description: "AI-first code editor with built-in AI assistance and chat",
    url: "https://cursor.sh",
    category: "ai-code",
    subcategory: "Code Editor",
    tags: ["AI", "Code Editor", "Development", "Chat", "Productivity"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://assets.cursor.sh/logo192.png", // Updated to real logo
    color: "#3b82f6",
    pros: ["AI chat", "Code completion", "Free tier", "VS Code compatible"],
    cons: ["New tool", "Limited features", "Internet required"],
    features: [
      "AI chat",
      "Code completion",
      "File editing",
      "Terminal integration",
    ],
    status: "active" as const,
    website: "https://cursor.sh",
    documentation: "https://cursor.sh/docs",
  },
  {
    name: "Replit",
    description:
      "AI-powered online IDE for coding, collaboration, and deployment",
    url: "https://replit.com",
    category: "ai-code",
    subcategory: "Online IDE",
    tags: ["AI", "Online IDE", "Collaboration", "Deployment", "Education"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://replit.com/public/images/logo.svg", // Updated to real logo
    color: "#f97316",
    pros: ["Online IDE", "Collaboration", "Deployment", "AI assistance"],
    cons: ["Limited resources", "Internet required", "Privacy concerns"],
    features: [
      "AI code completion",
      "Real-time collaboration",
      "Deployment",
      "Templates",
    ],
    status: "active" as const,
    website: "https://replit.com",
    documentation: "https://docs.replit.com",
  },

  // Business & Productivity
  {
    name: "Notion AI",
    description: "AI-powered workspace for notes, docs, and project management",
    url: "https://notion.so",
    category: "ai-business",
    subcategory: "Productivity",
    tags: ["AI", "Productivity", "Notes", "Collaboration", "Workspace"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png",
    color: "#000000",
    pros: [
      "All-in-one workspace",
      "Great collaboration",
      "Flexible structure",
      "AI assistance",
    ],
    cons: ["Learning curve", "Can be expensive", "Limited offline access"],
    features: ["Note taking", "Project management", "AI writing", "Templates"],
    status: "active" as const,
    website: "https://notion.so",
    documentation: "https://developers.notion.com",
  },
  {
    name: "Jasper",
    description:
      "AI content creation platform for marketing and business content",
    url: "https://jasper.ai",
    category: "ai-business",
    subcategory: "Content Creation",
    tags: ["AI", "Content", "Marketing", "Writing", "Business"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://assets-global.website-files.com/61e4e3c5e858c7e6c1e3e3e3/61e4e3c5e858c7e6c1e3e3e3_jasper-logo.svg", // Updated to real logo
    color: "#10b981",
    pros: ["Marketing focused", "Templates", "Brand voice", "SEO optimization"],
    cons: ["Expensive", "Limited free trial", "Learning curve"],
    features: [
      "Content generation",
      "SEO optimization",
      "Brand voice",
      "Templates",
    ],
    status: "active" as const,
    website: "https://jasper.ai",
    documentation: "https://jasper.ai/help",
  },
  {
    name: "Copy.ai",
    description: "AI copywriting tool for creating marketing content and copy",
    url: "https://copy.ai",
    category: "ai-business",
    subcategory: "Content Creation",
    tags: ["AI", "Copywriting", "Marketing", "Content", "Business"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://assets.copy.ai/assets/images/logos/copyai-logo.svg", // Updated to real logo
    color: "#8b5cf6",
    pros: ["Easy to use", "Templates", "Free tier", "Marketing focus"],
    cons: ["Limited features", "Quality varies", "Subscription required"],
    features: [
      "Copy generation",
      "Templates",
      "Brand voice",
      "Content optimization",
    ],
    status: "active" as const,
    website: "https://copy.ai",
    documentation: "https://copy.ai/help",
  },

  // Audio & Music
  {
    name: "Mubert",
    description: "AI music generation platform for creating original music",
    url: "https://mubert.com",
    category: "ai-audio",
    subcategory: "Music Generation",
    tags: ["AI", "Music", "Generation", "Creative", "Royalty-free"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Mubert_logo.svg/1200px-Mubert_logo.svg.png",
    color: "#ec4899",
    pros: [
      "Royalty-free music",
      "Easy to use",
      "Multiple genres",
      "API available",
    ],
    cons: ["Limited customization", "Quality varies", "Subscription required"],
    features: [
      "Music generation",
      "Genre selection",
      "Mood-based",
      "API access",
    ],
    status: "active" as const,
    website: "https://mubert.com",
    documentation: "https://mubert.com/api",
    apiAvailable: true,
    apiUrl: "https://mubert.com/api",
  },
  {
    name: "Descript",
    description: "AI-powered audio and video editing platform",
    url: "https://descript.com",
    category: "ai-audio",
    subcategory: "Audio Editing",
    tags: ["AI", "Audio", "Video", "Editing", "Podcasting"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Descript_logo.svg/1200px-Descript_logo.svg.png",
    color: "#3b82f6",
    pros: [
      "Text-based editing",
      "AI voice cloning",
      "Easy to use",
      "Podcast focused",
    ],
    cons: ["Expensive", "Learning curve", "Limited free features"],
    features: [
      "Text-based editing",
      "Voice cloning",
      "Transcription",
      "Podcast tools",
    ],
    status: "active" as const,
    website: "https://descript.com",
    documentation: "https://help.descript.com",
  },

  // Beauty & Fashion
  {
    name: "YouCam Makeup",
    description: "AI-powered beauty and makeup try-on app by Perfect Corp",
    url: "https://youcam.com",
    category: "ai-beauty",
    subcategory: "Beauty & Fashion",
    tags: ["AI", "Beauty", "Makeup", "Virtual Try-On", "Mobile"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://www.perfectcorp.com/img/youcam-logo.svg", // Updated to real logo
    color: "#f472b6",
    pros: ["Realistic try-on", "Multiple brands", "Easy to use", "Mobile app"],
    cons: [
      "Limited features in free version",
      "Privacy concerns",
      "In-app purchases",
    ],
    features: [
      "Virtual makeup",
      "Hair color",
      "Skin analysis",
      "Product recommendations",
    ],
    status: "active" as const,
    website: "https://youcam.com",
    documentation: "https://youcam.com/support",
  },

  // Additional Tools
  {
    name: "ChatGPT Plus",
    description:
      "Advanced AI assistant with GPT-4, plugins, and advanced features",
    url: "https://chat.openai.com",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Chat", "GPT-4", "Plugins", "Advanced"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    color: "#10a37f",
    pros: [
      "GPT-4 access",
      "Plugins support",
      "Advanced features",
      "Priority access",
    ],
    cons: ["Monthly subscription", "Limited free tier", "Plugin costs"],
    features: [
      "GPT-4 model",
      "Plugin ecosystem",
      "Code interpreter",
      "Advanced analysis",
    ],
    status: "active" as const,
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
  },
  {
    name: "Firefly",
    description:
      "Adobe's AI-powered creative suite for image generation and editing",
    url: "https://firefly.adobe.com",
    category: "ai-image",
    subcategory: "Creative Suite",
    tags: ["AI", "Adobe", "Creative", "Design", "Professional"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Adobe_Systems_logo_and_wordmark.svg",
    color: "#ff0000",
    pros: [
      "Adobe integration",
      "Professional quality",
      "Commercial use",
      "Creative Cloud",
    ],
    cons: ["Adobe subscription", "Limited free credits", "Learning curve"],
    features: [
      "Text-to-image",
      "Vector graphics",
      "3D generation",
      "Brand-safe content",
    ],
    status: "active" as const,
    website: "https://adobe.com/firefly",
    documentation: "https://helpx.adobe.com/firefly/user-guide.html",
  },
  {
    name: "Synthesia STUDIO",
    description:
      "Professional AI video creation platform for businesses and creators",
    url: "https://synthesia.io/studio",
    category: "ai-video",
    subcategory: "Video Creation",
    tags: ["AI", "Video", "Business", "Professional", "Avatars"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://uploads-ssl.webflow.com/5f6b8b7b8b7b8b7b8b7b8b7b/5f6b8b7b8b7b8b7b8b7b8b7b_synthesia-logo.svg", // Updated to real logo
    color: "#dc2626",
    pros: [
      "Professional avatars",
      "Business focus",
      "Custom branding",
      "High quality",
    ],
    cons: ["Expensive", "Enterprise pricing", "Limited customization"],
    features: [
      "AI avatars",
      "Custom branding",
      "Multi-language",
      "Professional templates",
    ],
    status: "active" as const,
    website: "https://synthesia.io",
    documentation: "https://help.synthesia.io",
  },
  {
    name: "Tabnine Pro",
    description:
      "Advanced AI code completion with team collaboration and security",
    url: "https://tabnine.com/pro",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "Team", "Security", "Enterprise"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://www.tabnine.com/images/logos/tabnine-logo.svg", // Updated to real logo
    color: "#3b82f6",
    pros: [
      "Team features",
      "Security focus",
      "Custom training",
      "Enterprise support",
    ],
    cons: ["Expensive", "Complex setup", "Limited free features"],
    features: [
      "Team collaboration",
      "Custom models",
      "Security compliance",
      "API access",
    ],
    status: "active" as const,
    website: "https://tabnine.com",
    documentation: "https://tabnine.com/docs",
  },
  {
    name: "Writesonic",
    description:
      "AI-powered content creation platform for marketing and business",
    url: "https://writesonic.com",
    category: "ai-business",
    subcategory: "Content Creation",
    tags: ["AI", "Content", "Marketing", "SEO", "Business"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://cdn.writesonic.com/static/images/logo.svg", // Updated to real logo
    color: "#8b5cf6",
    pros: ["SEO optimization", "Marketing focus", "Templates", "Free tier"],
    cons: ["Limited free credits", "Quality varies", "Subscription required"],
    features: [
      "SEO content",
      "Marketing copy",
      "Blog writing",
      "Product descriptions",
    ],
    status: "active" as const,
    website: "https://writesonic.com",
    documentation: "https://writesonic.com/help",
  },
  {
    name: "AIVA",
    description:
      "AI music composer for creating original compositions and soundtracks",
    url: "https://aiva.ai",
    category: "ai-audio",
    subcategory: "Music Composition",
    tags: ["AI", "Music", "Composition", "Soundtrack", "Creative"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://aiva.ai/images/logo192.png", // Updated to real logo
    color: "#06b6d4",
    pros: [
      "Original compositions",
      "Multiple genres",
      "Commercial licensing",
      "Easy to use",
    ],
    cons: ["Limited customization", "Subscription required", "Quality varies"],
    features: [
      "Music composition",
      "Genre selection",
      "Commercial licensing",
      "API access",
    ],
    status: "active" as const,
    website: "https://aiva.ai",
    documentation: "https://aiva.ai/docs",
    apiAvailable: true,
    apiUrl: "https://aiva.ai/api",
  },
  {
    name: "Perfect Corp",
    description:
      "AI-powered beauty technology platform for virtual try-on and analysis",
    url: "https://perfectcorp.com",
    category: "ai-beauty",
    subcategory: "Beauty Technology",
    tags: ["AI", "Beauty", "Technology", "Virtual Try-On", "Analysis"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://www.perfectcorp.com/img/perfectcorp-logo.svg", // Updated to real logo
    color: "#ec4899",
    pros: [
      "Advanced technology",
      "Multiple applications",
      "Professional use",
      "High accuracy",
    ],
    cons: ["Expensive", "Enterprise focus", "Limited consumer access"],
    features: [
      "Virtual try-on",
      "Skin analysis",
      "Hair color",
      "Fashion recommendations",
    ],
    status: "active" as const,
    website: "https://perfectcorp.com",
    documentation: "https://perfectcorp.com/developers",
  },
  {
    name: "Coursera AI",
    description:
      "AI-powered learning platform with personalized education paths",
    url: "https://coursera.org",
    category: "ai-education",
    subcategory: "Online Learning",
    tags: ["AI", "Education", "Courses", "Certification", "University"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Coursera_logo.svg",
    color: "#0056d2",
    pros: [
      "University partnerships",
      "Certifications",
      "AI courses",
      "Flexible learning",
    ],
    cons: ["Expensive courses", "Time commitment", "Internet required"],
    features: [
      "AI-powered learning",
      "University courses",
      "Certifications",
      "Flexible schedule",
    ],
    status: "active" as const,
    website: "https://coursera.org",
    documentation: "https://coursera.org/help",
  },
  {
    name: "Babylon Health",
    description:
      "AI-powered healthcare platform for symptom checking and consultations",
    url: "https://babylonhealth.com",
    category: "ai-health",
    subcategory: "Healthcare",
    tags: [
      "AI",
      "Healthcare",
      "Telemedicine",
      "Symptom Checker",
      "Consultations",
    ],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Babylon_Health_logo.svg/1200px-Babylon_Health_logo.svg.png",
    color: "#059669",
    pros: [
      "24/7 access",
      "AI diagnosis",
      "Telemedicine",
      "Professional doctors",
    ],
    cons: ["Limited coverage", "Subscription required", "Not emergency care"],
    features: [
      "Symptom checking",
      "AI diagnosis",
      "Video consultations",
      "Health monitoring",
    ],
    status: "active" as const,
    website: "https://babylonhealth.com",
    documentation: "https://babylonhealth.com/help",
  },
  {
    name: "DeepL",
    description:
      "AI-powered translation platform with superior accuracy and natural language",
    url: "https://deepl.com",
    category: "ai-business",
    subcategory: "Translation",
    tags: ["AI", "Translation", "Language", "Accuracy", "Professional"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://static.deepl.com/img/logo.svg", // Updated to real logo
    color: "#0f172a",
    pros: [
      "Superior accuracy",
      "Natural language",
      "Professional use",
      "API available",
    ],
    cons: ["Limited free tier", "Expensive", "Fewer languages"],
    features: [
      "High-quality translation",
      "Natural language",
      "Document translation",
      "API access",
    ],
    status: "active" as const,
    website: "https://deepl.com",
    documentation: "https://deepl.com/docs-api",
    apiAvailable: true,
    apiUrl: "https://deepl.com/docs-api",
  },
  {
    name: "Lumen5",
    description:
      "AI video creation platform for social media and marketing content",
    url: "https://lumen5.com",
    category: "ai-video",
    subcategory: "Social Media",
    tags: ["AI", "Video", "Social Media", "Marketing", "Content"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Lumen5_logo.svg/1200px-Lumen5_logo.svg.png",
    color: "#ef4444",
    pros: ["Social media focus", "Easy to use", "Templates", "Free tier"],
    cons: ["Limited customization", "Watermarks", "Subscription required"],
    features: [
      "Text-to-video",
      "Social media formats",
      "Templates",
      "Brand customization",
    ],
    status: "active" as const,
    website: "https://lumen5.com",
    documentation: "https://lumen5.com/help",
  },
  {
    name: "Beautiful.ai",
    description:
      "AI-powered presentation software for creating stunning slides",
    url: "https://beautiful.ai",
    category: "ai-business",
    subcategory: "Presentations",
    tags: ["AI", "Presentations", "Design", "Slides", "Business"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Beautiful.ai_logo.svg/1200px-Beautiful.ai_logo.svg.png",
    color: "#8b5cf6",
    pros: ["Beautiful designs", "AI assistance", "Templates", "Professional"],
    cons: ["Expensive", "Limited free trial", "Learning curve"],
    features: [
      "AI design suggestions",
      "Templates",
      "Real-time collaboration",
      "Brand customization",
    ],
    status: "active" as const,
    website: "https://beautiful.ai",
    documentation: "https://beautiful.ai/help",
  },
  {
    name: "Tome",
    description: "AI-powered storytelling and presentation platform",
    url: "https://tome.app",
    category: "ai-business",
    subcategory: "Presentations",
    tags: ["AI", "Storytelling", "Presentations", "Creative", "Narrative"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Tome_logo.svg/1200px-Tome_logo.svg.png",
    color: "#6366f1",
    pros: ["Unique storytelling", "AI generation", "Easy to use", "Free tier"],
    cons: ["Limited templates", "New platform", "Subscription required"],
    features: [
      "AI story generation",
      "Interactive presentations",
      "Templates",
      "Collaboration",
    ],
    status: "active" as const,
    website: "https://tome.app",
    documentation: "https://tome.app/help",
  },
  {
    name: "Gamma",
    description: "AI-powered presentation and document creation platform",
    url: "https://gamma.app",
    category: "ai-business",
    subcategory: "Presentations",
    tags: ["AI", "Presentations", "Documents", "Design", "Productivity"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Gamma_logo.svg/1200px-Gamma_logo.svg.png",
    color: "#10b981",
    pros: ["AI generation", "Beautiful designs", "Easy to use", "Free tier"],
    cons: ["Limited customization", "New platform", "Subscription required"],
    features: [
      "AI content generation",
      "Design suggestions",
      "Templates",
      "Real-time collaboration",
    ],
    status: "active" as const,
    website: "https://gamma.app",
    documentation: "https://gamma.app/help",
  },
  {
    name: "Jasper Art",
    description:
      "AI image generation tool integrated with Jasper's content platform",
    url: "https://jasper.ai/art",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Marketing", "Business", "Jasper"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://assets-global.website-files.com/61e4e3c5e858c7e6c1e3e3e3/61e4e3c5e858c7e6c1e3e3e3_jasper-logo.svg", // Updated to real logo
    color: "#10b981",
    pros: [
      "Marketing focus",
      "Jasper integration",
      "Easy to use",
      "Commercial use",
    ],
    cons: ["Expensive", "Limited features", "Subscription required"],
    features: [
      "Text-to-image",
      "Style presets",
      "Commercial licensing",
      "Jasper integration",
    ],
    status: "active" as const,
    website: "https://jasper.ai/art",
    documentation: "https://jasper.ai/help",
  },
  {
    name: "Leonardo.ai",
    description:
      "AI art generation platform for creating stunning digital artwork",
    url: "https://leonardo.ai",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Art", "Image Generation", "Creative", "Digital Art"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://leonardo.ai/logo192.png", // Updated to real logo
    color: "#f59e0b",
    pros: ["High quality", "Artistic focus", "Free tier", "Community features"],
    cons: ["Limited free credits", "Watermarks", "Subscription required"],
    features: [
      "Text-to-image",
      "Style training",
      "Community gallery",
      "Commercial licensing",
    ],
    status: "active" as const,
    website: "https://leonardo.ai",
    documentation: "https://leonardo.ai/help",
  },
  {
    name: "Playground AI",
    description:
      "AI image generation platform with advanced customization options",
    url: "https://playgroundai.com",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Customization", "Creative", "Advanced"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://playgroundai.com/logo192.png", // Updated to real logo
    color: "#3b82f6",
    pros: [
      "Advanced controls",
      "Multiple models",
      "Free tier",
      "Custom training",
    ],
    cons: ["Complex interface", "Learning curve", "Limited free credits"],
    features: [
      "Multiple AI models",
      "Advanced controls",
      "Custom training",
      "Commercial licensing",
    ],
    status: "active" as const,
    website: "https://playgroundai.com",
    documentation: "https://playgroundai.com/docs",
  },
  {
    name: "ElevenLabs",
    description: "AI voice generation and text-to-speech platform",
    url: "https://elevenlabs.io",
    category: "ai-audio",
    subcategory: "Voice Generation",
    tags: ["AI", "Voice", "Text-to-Speech", "Voice Cloning", "Audio"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://elevenlabs.io/logo192.png", // Updated to real logo
    color: "#8b5cf6",
    pros: [
      "High quality",
      "Voice cloning",
      "Multiple languages",
      "API available",
    ],
    cons: ["Expensive", "Limited free credits", "Privacy concerns"],
    features: [
      "Text-to-speech",
      "Voice cloning",
      "Multiple languages",
      "API access",
    ],
    status: "active" as const,
    website: "https://elevenlabs.io",
    documentation: "https://elevenlabs.io/docs",
    apiAvailable: true,
    apiUrl: "https://elevenlabs.io/docs",
  },
  {
    name: "Uberduck",
    description: "AI voice generation platform for creating custom voices",
    url: "https://uberduck.ai",
    category: "ai-audio",
    subcategory: "Voice Generation",
    tags: ["AI", "Voice", "Generation", "Custom", "Creative"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://uberduck.ai/logo192.png", // Updated to real logo
    color: "#dc2626",
    pros: ["Custom voices", "Easy to use", "Free tier", "Community voices"],
    cons: ["Limited quality", "Privacy concerns", "Subscription required"],
    features: [
      "Voice cloning",
      "Text-to-speech",
      "Community voices",
      "API access",
    ],
    status: "active" as const,
    website: "https://uberduck.ai",
    documentation: "https://uberduck.ai/docs",
    apiAvailable: true,
    apiUrl: "https://uberduck.ai/docs",
  },
  {
    name: "CodeWhisperer",
    description: "Amazon's AI code generation and completion tool",
    url: "https://aws.amazon.com/codewhisperer",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "AWS", "Development", "IDE"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg",
    color: "#ff9900",
    pros: [
      "Free for individuals",
      "AWS integration",
      "Security focused",
      "IDE support",
    ],
    cons: ["AWS focused", "Limited languages", "Internet required"],
    features: [
      "Code completion",
      "Security scanning",
      "IDE integration",
      "AWS integration",
    ],
    status: "active" as const,
    website: "https://aws.amazon.com/codewhisperer",
    documentation: "https://docs.aws.amazon.com/codewhisperer",
  },
  {
    name: "Tabnine",
    description: "AI code completion tool for developers",
    url: "https://tabnine.com",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "Completion", "IDE", "Development"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://www.tabnine.com/images/logos/tabnine-logo.svg", // Updated to real logo
    color: "#3b82f6",
    pros: ["Fast completion", "Multiple languages", "IDE support", "Free tier"],
    cons: ["Limited features", "Privacy concerns", "Subscription required"],
    features: [
      "Code completion",
      "Multiple languages",
      "IDE integration",
      "Custom training",
    ],
    status: "active" as const,
    website: "https://tabnine.com",
    documentation: "https://tabnine.com/docs",
  },
  {
    name: "Hugging Face",
    description: "AI model hub and platform for machine learning models",
    url: "https://huggingface.co",
    category: "ai-code",
    subcategory: "Machine Learning",
    tags: ["AI", "Machine Learning", "Models", "Open Source", "Community"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://huggingface.co/front/assets/huggingface_logo-noborder.svg", // Updated to real logo
    color: "#fbbf24",
    pros: ["Huge model library", "Open source", "Community", "Free tier"],
    cons: ["Technical", "Learning curve", "Limited support"],
    features: ["Model hosting", "Inference API", "Training", "Community"],
    status: "active" as const,
    website: "https://huggingface.co",
    documentation: "https://huggingface.co/docs",
    apiAvailable: true,
    apiUrl: "https://huggingface.co/docs/api-inference",
  },
  {
    name: "TensorFlow",
    description: "Open-source machine learning framework by Google",
    url: "https://tensorflow.org",
    category: "ai-code",
    subcategory: "Machine Learning",
    tags: ["AI", "Machine Learning", "Framework", "Google", "Open Source"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg",
    color: "#ff6f00",
    pros: ["Open source", "Google backed", "Comprehensive", "Community"],
    cons: ["Complex", "Learning curve", "Hardware requirements"],
    features: [
      "Deep learning",
      "TensorFlow.js",
      "Model deployment",
      "Research tools",
    ],
    status: "active" as const,
    website: "https://tensorflow.org",
    documentation: "https://tensorflow.org/guide",
  },
  {
    name: "PyTorch",
    description: "Open-source machine learning framework by Meta",
    url: "https://pytorch.org",
    category: "ai-code",
    subcategory: "Machine Learning",
    tags: ["AI", "Machine Learning", "Framework", "Meta", "Open Source"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg",
    color: "#ee4c2c",
    pros: ["Open source", "Meta backed", "Python native", "Research focused"],
    cons: ["Complex", "Learning curve", "Hardware requirements"],
    features: [
      "Deep learning",
      "Research tools",
      "Model deployment",
      "Community",
    ],
    status: "active" as const,
    website: "https://pytorch.org",
    documentation: "https://pytorch.org/docs",
  },
  // AI Writing Tools
  {
    name: "Jasper",
    description:
      "AI writing assistant for marketing, content, and creative writing",
    url: "https://jasper.ai",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Writing", "Marketing", "Content", "Copywriting"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Jasper_AI_logo.svg",
    color: "#ff6b35",
    pros: [
      "High-quality content",
      "Marketing focused",
      "Templates",
      "SEO optimized",
    ],
    cons: ["Expensive", "Limited free tier", "Requires editing"],
    features: [
      "Blog writing",
      "Marketing copy",
      "Email campaigns",
      "Social media",
    ],
    status: "active" as const,
    website: "https://jasper.ai",
    documentation: "https://jasper.ai/help",
    apiAvailable: true,
    apiUrl: "https://jasper.ai/api",
  },
  {
    name: "Copy.ai",
    description: "AI copywriting tool for marketing and business content",
    url: "https://copy.ai",
    category: "ai-writing",
    subcategory: "Copywriting",
    tags: ["AI", "Copywriting", "Marketing", "Business", "Content"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Copy.ai_logo.svg",
    color: "#6366f1",
    pros: ["Easy to use", "Marketing templates", "Free tier", "Quick results"],
    cons: ["Limited creativity", "Requires editing", "Repetitive content"],
    features: [
      "Ad copy",
      "Product descriptions",
      "Email marketing",
      "Social media",
    ],
    status: "active" as const,
    website: "https://copy.ai",
    documentation: "https://copy.ai/help",
    apiAvailable: true,
    apiUrl: "https://copy.ai/api",
  },
  {
    name: "Writesonic",
    description: "AI writing platform for blogs, ads, and business content",
    url: "https://writesonic.com",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Writing", "Blogging", "Marketing", "SEO"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Writesonic_logo.svg",
    color: "#8b5cf6",
    pros: ["SEO optimized", "Blog writing", "Multiple languages", "Templates"],
    cons: ["Limited free credits", "Quality varies", "Requires editing"],
    features: [
      "Blog articles",
      "Landing pages",
      "Product descriptions",
      "SEO content",
    ],
    status: "active" as const,
    website: "https://writesonic.com",
    documentation: "https://writesonic.com/docs",
    apiAvailable: true,
    apiUrl: "https://writesonic.com/api",
  },
  {
    name: "Grammarly",
    description: "AI-powered writing assistant for grammar, style, and tone",
    url: "https://grammarly.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Grammar", "Writing", "Editing", "Style"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Grammarly_logo.svg",
    color: "#15c39a",
    pros: [
      "Excellent grammar",
      "Style suggestions",
      "Browser integration",
      "Free tier",
    ],
    cons: ["Limited AI writing", "Premium expensive", "Privacy concerns"],
    features: [
      "Grammar checking",
      "Style suggestions",
      "Tone detection",
      "Plagiarism check",
    ],
    status: "active" as const,
    website: "https://grammarly.com",
    documentation: "https://grammarly.com/help",
    apiAvailable: true,
    apiUrl: "https://grammarly.com/api",
  },
  {
    name: "ProWritingAid",
    description: "Comprehensive writing editor with AI-powered suggestions",
    url: "https://prowritingaid.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Writing", "Editing", "Grammar", "Style"],
    featured: false,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/ProWritingAid_logo.svg",
    color: "#dc2626",
    pros: [
      "Comprehensive editing",
      "Detailed reports",
      "Multiple integrations",
      "Academic focus",
    ],
    cons: ["Expensive", "Complex interface", "No free tier"],
    features: [
      "Grammar checking",
      "Style analysis",
      "Readability scores",
      "Writing reports",
    ],
    status: "active" as const,
    website: "https://prowritingaid.com",
    documentation: "https://prowritingaid.com/help",
    apiAvailable: false,
  },
  {
    name: "Hemingway Editor",
    description: "Writing app that makes your writing bold and clear",
    url: "https://hemingwayapp.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Writing", "Clarity", "Style", "Editing"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Hemingway_Editor_logo.svg",
    color: "#f59e0b",
    pros: [
      "Improves clarity",
      "Simple interface",
      "Free web version",
      "Readability focus",
    ],
    cons: ["Limited features", "No grammar check", "Basic AI"],
    features: [
      "Readability analysis",
      "Style suggestions",
      "Sentence structure",
      "Word choice",
    ],
    status: "active" as const,
    website: "https://hemingwayapp.com",
    documentation: "https://hemingwayapp.com/help",
    apiAvailable: false,
  },
  {
    name: "QuillBot",
    description: "AI-powered paraphrasing and writing tool",
    url: "https://quillbot.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Paraphrasing", "Writing", "Grammar", "Translation"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/QuillBot_logo.svg",
    color: "#3b82f6",
    pros: [
      "Excellent paraphrasing",
      "Grammar checker",
      "Free tier",
      "Multiple languages",
    ],
    cons: ["Limited creativity", "Repetitive suggestions", "Premium expensive"],
    features: [
      "Paraphrasing",
      "Grammar checking",
      "Summarizer",
      "Citation generator",
    ],
    status: "active" as const,
    website: "https://quillbot.com",
    documentation: "https://quillbot.com/help",
    apiAvailable: true,
    apiUrl: "https://quillbot.com/api",
  },
  {
    name: "Rytr",
    description: "AI writing assistant for content creation and copywriting",
    url: "https://rytr.me",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Writing", "Content", "Copywriting", "Marketing"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Rytr_logo.svg",
    color: "#10b981",
    pros: ["Affordable", "Multiple use cases", "SEO optimized", "Templates"],
    cons: ["Limited creativity", "Quality varies", "Basic interface"],
    features: [
      "Blog writing",
      "Marketing copy",
      "Email campaigns",
      "Social media",
    ],
    status: "active" as const,
    website: "https://rytr.me",
    documentation: "https://rytr.me/help",
    apiAvailable: true,
    apiUrl: "https://rytr.me/api",
  },
  {
    name: "ContentBot",
    description: "AI content generator for blogs, articles, and marketing",
    url: "https://contentbot.ai",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Content", "Blogging", "Marketing", "SEO"],
    featured: false,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/6d/ContentBot_logo.svg",
    color: "#7c3aed",
    pros: [
      "Long-form content",
      "SEO focused",
      "Research integration",
      "High quality",
    ],
    cons: ["Expensive", "No free tier", "Limited templates"],
    features: [
      "Blog articles",
      "Research papers",
      "SEO content",
      "Content planning",
    ],
    status: "active" as const,
    website: "https://contentbot.ai",
    documentation: "https://contentbot.ai/docs",
    apiAvailable: true,
    apiUrl: "https://contentbot.ai/api",
  },
  {
    name: "Wordtune",
    description:
      "AI writing assistant that helps you express your ideas better",
    url: "https://wordtune.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Writing", "Expression", "Style", "Clarity"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Wordtune_logo.svg",
    color: "#ef4444",
    pros: [
      "Improves expression",
      "Browser integration",
      "Free tier",
      "Multiple styles",
    ],
    cons: ["Limited features", "Requires context", "Premium expensive"],
    features: [
      "Sentence rewriting",
      "Tone adjustment",
      "Style suggestions",
      "Clarity improvement",
    ],
    status: "active" as const,
    website: "https://wordtune.com",
    documentation: "https://wordtune.com/help",
    apiAvailable: true,
    apiUrl: "https://wordtune.com/api",
  },
  // Additional AI Chat Tools
  {
    name: "Character.AI",
    description:
      "AI chatbot platform for creating and chatting with AI characters",
    url: "https://character.ai",
    category: "ai-chat",
    subcategory: "Character Chat",
    tags: ["AI", "Chat", "Characters", "Entertainment", "Roleplay"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Character.AI_logo.svg",
    color: "#8b5cf6",
    pros: ["Unique characters", "Entertaining", "Creative", "Free to use"],
    cons: ["Limited utility", "No API", "Privacy concerns", "Addictive"],
    features: [
      "Character creation",
      "Roleplay chat",
      "Multiple personalities",
      "Creative writing",
    ],
    status: "active" as const,
    website: "https://character.ai",
    documentation: "https://character.ai/help",
    apiAvailable: false,
  },
  {
    name: "Poe",
    description: "AI chat platform with access to multiple AI models",
    url: "https://poe.com",
    category: "ai-chat",
    subcategory: "Multi-Model Chat",
    tags: ["AI", "Chat", "Multiple Models", "Claude", "GPT"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Poe_logo.svg",
    color: "#06b6d4",
    pros: ["Multiple AI models", "Free tier", "Easy to use", "Mobile app"],
    cons: [
      "Limited features",
      "No API",
      "Model restrictions",
      "Privacy concerns",
    ],
    features: [
      "Multiple AI models",
      "Chat history",
      "Mobile app",
      "Easy switching",
    ],
    status: "active" as const,
    website: "https://poe.com",
    documentation: "https://poe.com/help",
    apiAvailable: false,
  },
  // Additional AI Image Tools
  {
    name: "Leonardo.AI",
    description: "AI art generation platform with advanced creative tools",
    url: "https://leonardo.ai",
    category: "ai-image",
    subcategory: "Art Generation",
    tags: ["AI", "Art", "Generation", "Creative", "Design"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Leonardo.AI_logo.svg",
    color: "#f97316",
    pros: ["High quality", "Creative tools", "Community", "Free tier"],
    cons: ["Limited credits", "Complex interface", "Learning curve"],
    features: [
      "Image generation",
      "Creative tools",
      "Community gallery",
      "Model training",
    ],
    status: "active" as const,
    website: "https://leonardo.ai",
    documentation: "https://leonardo.ai/docs",
    apiAvailable: true,
    apiUrl: "https://leonardo.ai/api",
  },
  {
    name: "Playground AI",
    description: "Free AI image generation platform with multiple models",
    url: "https://playgroundai.com",
    category: "ai-image",
    subcategory: "Art Generation",
    tags: ["AI", "Art", "Free", "Generation", "Creative"],
    featured: false,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Playground_AI_logo.svg/1200px-Playground_AI_logo.svg.png",
    color: "#10b981",
    pros: ["Completely free", "Multiple models", "High quality", "Easy to use"],
    cons: ["Limited features", "No API", "Basic interface", "Queue system"],
    features: [
      "Free generation",
      "Multiple models",
      "Basic editing",
      "Community gallery",
    ],
    status: "active" as const,
    website: "https://playgroundai.com",
    documentation: "https://playgroundai.com/help",
    apiAvailable: false,
  },
  // Additional AI Video Tools
  {
    name: "Runway ML",
    description: "AI-powered video editing and generation platform",
    url: "https://runwayml.com",
    category: "ai-video",
    subcategory: "Video Editing",
    tags: ["AI", "Video", "Editing", "Generation", "Creative"],
    featured: false,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Runway_ML_logo.svg",
    color: "#6366f1",
    pros: [
      "Professional tools",
      "High quality",
      "Multiple features",
      "Industry standard",
    ],
    cons: ["Expensive", "Complex", "Learning curve", "No free tier"],
    features: [
      "Video generation",
      "Motion tracking",
      "Green screen removal",
      "Text to video",
    ],
    status: "active" as const,
    website: "https://runwayml.com",
    documentation: "https://runwayml.com/docs",
    apiAvailable: true,
    apiUrl: "https://runwayml.com/api",
  },
  {
    name: "Synthesia",
    description: "AI video generation platform for creating talking avatars",
    url: "https://synthesia.io",
    category: "ai-video",
    subcategory: "Avatar Generation",
    tags: ["AI", "Video", "Avatars", "Talking", "Business"],
    featured: false,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Synthesia_logo.svg",
    color: "#dc2626",
    pros: [
      "Realistic avatars",
      "Multiple languages",
      "Business focused",
      "High quality",
    ],
    cons: ["Expensive", "Limited customization", "No free tier"],
    features: [
      "Talking avatars",
      "Multiple languages",
      "Custom avatars",
      "Video templates",
    ],
    status: "active" as const,
    website: "https://synthesia.io",
    documentation: "https://synthesia.io/docs",
    apiAvailable: true,
    apiUrl: "https://synthesia.io/api",
  },
  // Additional AI Code Tools
  {
    name: "Replit",
    description: "Online IDE with AI coding assistance and collaboration",
    url: "https://replit.com",
    category: "ai-code",
    subcategory: "Development Environment",
    tags: ["AI", "Coding", "IDE", "Collaboration", "Online"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Replit_logo.svg",
    color: "#f59e0b",
    pros: ["Online IDE", "AI assistance", "Collaboration", "Free tier"],
    cons: ["Limited resources", "Internet dependent", "Basic features"],
    features: [
      "Online coding",
      "AI assistance",
      "Real-time collaboration",
      "Deployment",
    ],
    status: "active" as const,
    website: "https://replit.com",
    documentation: "https://replit.com/docs",
    apiAvailable: true,
    apiUrl: "https://replit.com/api",
  },
  {
    name: "CodeWhisperer",
    description: "Amazon's AI coding assistant for developers",
    url: "https://aws.amazon.com/codewhisperer",
    category: "ai-code",
    subcategory: "Code Assistant",
    tags: ["AI", "Coding", "AWS", "Security", "IDE"],
    featured: false,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/9f/CodeWhisperer_logo.svg",
    color: "#ff9900",
    pros: [
      "Free for individuals",
      "Security focused",
      "AWS integration",
      "IDE support",
    ],
    cons: ["Limited features", "AWS dependent", "Basic AI"],
    features: [
      "Code suggestions",
      "Security scanning",
      "IDE integration",
      "AWS services",
    ],
    status: "active" as const,
    website: "https://aws.amazon.com/codewhisperer",
    documentation: "https://docs.aws.amazon.com/codewhisperer",
    apiAvailable: false,
  },
  // Additional AI Business Tools
  {
    name: "Jarvis",
    description: "AI assistant for business automation and productivity",
    url: "https://jarvis.ai",
    category: "ai-business",
    subcategory: "Business Automation",
    tags: ["AI", "Business", "Automation", "Productivity", "Assistant"],
    featured: false,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Jarvis_AI_logo.svg",
    color: "#3b82f6",
    pros: ["Business focused", "Automation", "Integration", "Customizable"],
    cons: ["Expensive", "Complex setup", "No free tier"],
    features: [
      "Business automation",
      "Data analysis",
      "Report generation",
      "Integration",
    ],
    status: "active" as const,
    website: "https://jarvis.ai",
    documentation: "https://jarvis.ai/docs",
    apiAvailable: true,
    apiUrl: "https://jarvis.ai/api",
  },
  {
    name: "Otter.ai",
    description: "AI-powered meeting transcription and note-taking",
    url: "https://otter.ai",
    category: "ai-business",
    subcategory: "Transcription",
    tags: ["AI", "Transcription", "Meetings", "Notes", "Business"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Otter.ai_logo.svg",
    color: "#10b981",
    pros: [
      "Accurate transcription",
      "Meeting notes",
      "Speaker identification",
      "Free tier",
    ],
    cons: ["Limited free minutes", "Privacy concerns", "Requires good audio"],
    features: [
      "Meeting transcription",
      "Speaker identification",
      "Note taking",
      "Integration",
    ],
    status: "active" as const,
    website: "https://otter.ai",
    documentation: "https://otter.ai/help",
    apiAvailable: true,
    apiUrl: "https://otter.ai/api",
  },
  // Additional AI Education Tools
  {
    name: "Duolingo",
    description: "AI-powered language learning platform",
    url: "https://duolingo.com",
    category: "ai-education",
    subcategory: "Language Learning",
    tags: ["AI", "Education", "Language", "Learning", "Gamification"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Duolingo_logo.svg",
    color: "#58cc02",
    pros: [
      "Gamified learning",
      "Multiple languages",
      "Free tier",
      "Mobile app",
    ],
    cons: ["Limited depth", "Repetitive", "Premium expensive"],
    features: [
      "Language learning",
      "Gamification",
      "Progress tracking",
      "Mobile app",
    ],
    status: "active" as const,
    website: "https://duolingo.com",
    documentation: "https://duolingo.com/help",
    apiAvailable: false,
  },
  {
    name: "Khan Academy",
    description: "AI-enhanced educational platform for various subjects",
    url: "https://khanacademy.org",
    category: "ai-education",
    subcategory: "General Education",
    tags: ["AI", "Education", "Learning", "Free", "Comprehensive"],
    featured: false,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Khan_Academy_logo.svg",
    color: "#14bf96",
    pros: [
      "Completely free",
      "Comprehensive",
      "Multiple subjects",
      "Adaptive learning",
    ],
    cons: ["Limited AI features", "Basic interface", "No certificates"],
    features: [
      "Multiple subjects",
      "Adaptive learning",
      "Progress tracking",
      "Practice exercises",
    ],
    status: "active" as const,
    website: "https://khanacademy.org",
    documentation: "https://khanacademy.org/help",
    apiAvailable: false,
  },
  // Additional AI Health Tools
  {
    name: "Ada Health",
    description: "AI-powered health assessment and symptom checker",
    url: "https://ada.com",
    category: "ai-health",
    subcategory: "Health Assessment",
    tags: ["AI", "Health", "Assessment", "Symptoms", "Medical"],
    featured: false,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Ada_Health_logo.svg",
    color: "#3b82f6",
    pros: [
      "Free health assessment",
      "Comprehensive",
      "Medical database",
      "Easy to use",
    ],
    cons: [
      "Not a replacement for doctors",
      "Limited accuracy",
      "Privacy concerns",
    ],
    features: [
      "Symptom checker",
      "Health assessment",
      "Medical information",
      "Appointment booking",
    ],
    status: "active" as const,
    website: "https://ada.com",
    documentation: "https://ada.com/help",
    apiAvailable: false,
  },
  {
    name: "Woebot",
    description: "AI mental health chatbot for emotional support",
    url: "https://woebot.io",
    category: "ai-health",
    subcategory: "Mental Health",
    tags: ["AI", "Mental Health", "Chatbot", "Support", "Therapy"],
    featured: false,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Woebot_logo.svg",
    color: "#8b5cf6",
    pros: [
      "Mental health support",
      "24/7 availability",
      "Evidence-based",
      "Free tier",
    ],
    cons: [
      "Not a replacement for therapy",
      "Limited personalization",
      "Privacy concerns",
    ],
    features: [
      "Mental health support",
      "Mood tracking",
      "CBT techniques",
      "Daily check-ins",
    ],
    status: "active" as const,
    website: "https://woebot.io",
    documentation: "https://woebot.io/help",
    apiAvailable: false,
  },
];

export async function seedDatabase() {
  try {
    console.log("Starting database seeding...");

    // Create admin user
    const usersCollection = await getUsersCollection();
    const adminExists = await usersCollection.findOne({
      email: "heylelyaka@gmail.com",
    });

    if (!adminExists) {
      const hashedPassword = await bcrypt.hash("admin123", 12);
      const adminUser = createUser({
        email: "heylelyaka@gmail.com",
        name: "Heylel Yaka",
        password: hashedPassword,
        role: "admin",
      });

      await usersCollection.insertOne(adminUser);
      console.log("Admin user created");
    }

    // Seed tools
    const toolsCollection = await getToolsCollection();

    for (const toolData of initialTools) {
      const existingTool = await toolsCollection.findOne({
        name: toolData.name,
      });

      if (!existingTool) {
        const tool = createTool(toolData);
        await toolsCollection.insertOne(tool);
        console.log(`Tool "${toolData.name}" created`);
      }
    }

    console.log("Database seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}
