import { getToolsCollection, getUsersCollection } from "./db";
import { createTool } from "./models/Tool";
import { createUser } from "./models/User";
import bcrypt from "bcryptjs";

const initialTools = [
  // Chat & Language Models
  {
    name: "ChatGPT",
    description:
      "Advanced AI language model for conversation, writing, and content creation",
    url: "https://chat.openai.com",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Chat", "Writing", "OpenAI", "GPT-4"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    color: "#10a37f",
    pros: [
      "Powerful language model",
      "Great for writing",
      "Easy to use",
      "Regular updates",
    ],
    cons: ["Can be expensive", "Sometimes inaccurate", "Limited context"],
    features: [
      "Text generation",
      "Code assistance",
      "Translation",
      "Creative writing",
    ],
    status: "active" as const,
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
    apiAvailable: true,
    apiUrl: "https://platform.openai.com/docs/api-reference",
  },
  {
    name: "Claude",
    description:
      "Anthropic's AI assistant for writing, analysis, and creative tasks",
    url: "https://claude.ai",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Writing", "Analysis", "Anthropic", "Claude"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/86/Anthropic_logo.svg",
    color: "#d97706",
    pros: ["Excellent writing", "Good reasoning", "Safe AI", "File uploads"],
    cons: ["Limited availability", "No mobile app", "Subscription required"],
    features: [
      "Text analysis",
      "File processing",
      "Creative writing",
      "Code assistance",
    ],
    status: "active" as const,
    website: "https://anthropic.com",
    documentation: "https://docs.anthropic.com",
  },
  {
    name: "Bard",
    description:
      "Google's AI chatbot for creative collaboration and information",
    url: "https://bard.google.com",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Chat", "Google", "Creative", "Information"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg",
    color: "#4285f4",
    pros: [
      "Free to use",
      "Real-time information",
      "Multimodal",
      "Google integration",
    ],
    cons: ["Limited availability", "Sometimes inaccurate", "Privacy concerns"],
    features: [
      "Text generation",
      "Image analysis",
      "Web search",
      "Creative writing",
    ],
    status: "active" as const,
    website: "https://bard.google.com",
    documentation: "https://bard.google.com/faq",
  },
  {
    name: "Perplexity AI",
    description:
      "AI-powered search engine that provides accurate answers with sources",
    url: "https://perplexity.ai",
    category: "ai-chat",
    subcategory: "Search & Research",
    tags: ["AI", "Search", "Research", "Sources", "Accuracy"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://perplexity.ai/favicon.ico",
    color: "#6366f1",
    pros: [
      "Accurate answers",
      "Source citations",
      "Real-time search",
      "Free tier",
    ],
    cons: [
      "Limited features in free version",
      "Sometimes slow",
      "Limited context",
    ],
    features: [
      "Web search",
      "Source citations",
      "Multiple perspectives",
      "Real-time data",
    ],
    status: "active" as const,
    website: "https://perplexity.ai",
    documentation: "https://docs.perplexity.ai",
  },

  // Image Generation
  {
    name: "Midjourney",
    description:
      "AI-powered image generation tool for creating stunning artwork and designs",
    url: "https://midjourney.com",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Art", "Design", "Creative"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://midjourney.com/favicon.ico",
    color: "#8b5cf6",
    pros: [
      "High-quality images",
      "Creative control",
      "Fast generation",
      "Artistic style",
    ],
    cons: ["Paid service", "Discord-based", "Limited free tier"],
    features: [
      "Image generation",
      "Style variations",
      "Upscaling",
      "Custom prompts",
    ],
    status: "active" as const,
    website: "https://midjourney.com",
    documentation: "https://docs.midjourney.com",
  },
  {
    name: "DALL-E",
    description:
      "OpenAI's AI system for creating realistic images from text descriptions",
    url: "https://openai.com/dall-e-2",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "OpenAI", "Text-to-Image", "Creative"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg",
    color: "#10a37f",
    pros: [
      "High quality",
      "Easy to use",
      "Good editing tools",
      "API available",
    ],
    cons: ["Expensive", "Limited free credits", "Content restrictions"],
    features: ["Text-to-image", "Image editing", "Variations", "Outpainting"],
    status: "active" as const,
    website: "https://openai.com/dall-e-2",
    documentation: "https://platform.openai.com/docs/guides/images",
    apiAvailable: true,
    apiUrl: "https://platform.openai.com/docs/api-reference/images",
  },
  {
    name: "Stable Diffusion",
    description:
      "Open-source AI image generation model for creating art and designs",
    url: "https://stability.ai",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Open Source", "Art", "Local"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://stability.ai/favicon.ico",
    color: "#059669",
    pros: [
      "Open source",
      "Local deployment",
      "Customizable",
      "No usage limits",
    ],
    cons: ["Technical setup", "Hardware requirements", "Quality varies"],
    features: [
      "Image generation",
      "Style transfer",
      "Inpainting",
      "Custom models",
    ],
    status: "active" as const,
    website: "https://stability.ai",
    documentation: "https://github.com/CompVis/stable-diffusion",
    apiAvailable: true,
    apiUrl: "https://platform.stability.ai",
  },
  {
    name: "Canva AI",
    description:
      "AI-powered design tool for creating professional graphics and presentations",
    url: "https://canva.com",
    category: "ai-image",
    subcategory: "Design Tools",
    tags: ["AI", "Design", "Graphics", "Templates", "Collaboration"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg",
    color: "#00c4cc",
    pros: ["Easy to use", "Templates", "Collaboration", "AI features"],
    cons: ["Limited free features", "Watermarks", "Internet required"],
    features: [
      "AI image generation",
      "Templates",
      "Collaboration",
      "Brand kit",
    ],
    status: "active" as const,
    website: "https://canva.com",
    documentation: "https://www.canva.com/help/",
  },

  // Video Generation
  {
    name: "Runway ML",
    description: "AI video generation and editing platform for creators",
    url: "https://runwayml.com",
    category: "ai-video",
    subcategory: "Video Generation",
    tags: ["AI", "Video", "Editing", "Creative", "Film"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://runwayml.com/favicon.ico",
    color: "#7c3aed",
    pros: [
      "Professional quality",
      "Multiple tools",
      "Easy interface",
      "Regular updates",
    ],
    cons: ["Expensive", "Learning curve", "Limited free tier"],
    features: [
      "Video generation",
      "Object removal",
      "Motion tracking",
      "Green screen",
    ],
    status: "active" as const,
    website: "https://runwayml.com",
    documentation: "https://runwayml.com/docs",
  },
  {
    name: "Synthesia",
    description:
      "AI video generation platform for creating talking head videos",
    url: "https://synthesia.io",
    category: "ai-video",
    subcategory: "Video Generation",
    tags: ["AI", "Video", "Avatars", "Training", "Business"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://synthesia.io/favicon.ico",
    color: "#dc2626",
    pros: [
      "Professional avatars",
      "Easy to use",
      "Multiple languages",
      "Custom avatars",
    ],
    cons: ["Expensive", "Limited customization", "Subscription required"],
    features: [
      "AI avatars",
      "Text-to-speech",
      "Multiple languages",
      "Custom branding",
    ],
    status: "active" as const,
    website: "https://synthesia.io",
    documentation: "https://help.synthesia.io",
  },
  {
    name: "Pika Labs",
    description:
      "AI-powered video generation tool for creating short videos from text",
    url: "https://pika.art",
    category: "ai-video",
    subcategory: "Video Generation",
    tags: ["AI", "Video", "Text-to-Video", "Creative", "Short-form"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://pika.art/favicon.ico",
    color: "#f59e0b",
    pros: ["Easy to use", "Fast generation", "Good quality", "Free tier"],
    cons: ["Limited duration", "Watermarks", "Limited customization"],
    features: [
      "Text-to-video",
      "Image-to-video",
      "Style transfer",
      "Video editing",
    ],
    status: "active" as const,
    website: "https://pika.art",
    documentation: "https://pika.art/docs",
  },

  // Code & Development
  {
    name: "GitHub Copilot",
    description: "AI-powered code completion and pair programming assistant",
    url: "https://github.com/features/copilot",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "Development", "GitHub", "IDE"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg",
    color: "#24292e",
    pros: [
      "Excellent code completion",
      "IDE integration",
      "Multi-language support",
      "Context aware",
    ],
    cons: [
      "Subscription required",
      "Sometimes suggests wrong code",
      "Privacy concerns",
    ],
    features: [
      "Code completion",
      "Function generation",
      "Documentation",
      "Test generation",
    ],
    status: "active" as const,
    website: "https://github.com",
    documentation: "https://docs.github.com/en/copilot",
  },
  {
    name: "Cursor",
    description: "AI-first code editor with built-in AI assistance and chat",
    url: "https://cursor.sh",
    category: "ai-code",
    subcategory: "Code Editor",
    tags: ["AI", "Code Editor", "Development", "Chat", "Productivity"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://cursor.sh/favicon.ico",
    color: "#3b82f6",
    pros: ["AI chat", "Code completion", "Free tier", "VS Code compatible"],
    cons: ["New tool", "Limited features", "Internet required"],
    features: [
      "AI chat",
      "Code completion",
      "File editing",
      "Terminal integration",
    ],
    status: "active" as const,
    website: "https://cursor.sh",
    documentation: "https://cursor.sh/docs",
  },
  {
    name: "Replit",
    description:
      "AI-powered online IDE for coding, collaboration, and deployment",
    url: "https://replit.com",
    category: "ai-code",
    subcategory: "Online IDE",
    tags: ["AI", "Online IDE", "Collaboration", "Deployment", "Education"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://replit.com/favicon.ico",
    color: "#f97316",
    pros: ["Online IDE", "Collaboration", "Deployment", "AI assistance"],
    cons: ["Limited resources", "Internet required", "Privacy concerns"],
    features: [
      "AI code completion",
      "Real-time collaboration",
      "Deployment",
      "Templates",
    ],
    status: "active" as const,
    website: "https://replit.com",
    documentation: "https://docs.replit.com",
  },

  // Business & Productivity
  {
    name: "Notion AI",
    description: "AI-powered workspace for notes, docs, and project management",
    url: "https://notion.so",
    category: "ai-business",
    subcategory: "Productivity",
    tags: ["AI", "Productivity", "Notes", "Collaboration", "Workspace"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png",
    color: "#000000",
    pros: [
      "All-in-one workspace",
      "Great collaboration",
      "Flexible structure",
      "AI assistance",
    ],
    cons: ["Learning curve", "Can be expensive", "Limited offline access"],
    features: ["Note taking", "Project management", "AI writing", "Templates"],
    status: "active" as const,
    website: "https://notion.so",
    documentation: "https://developers.notion.com",
  },
  {
    name: "Jasper",
    description:
      "AI content creation platform for marketing and business content",
    url: "https://jasper.ai",
    category: "ai-business",
    subcategory: "Content Creation",
    tags: ["AI", "Content", "Marketing", "Writing", "Business"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://jasper.ai/favicon.ico",
    color: "#10b981",
    pros: ["Marketing focused", "Templates", "Brand voice", "SEO optimization"],
    cons: ["Expensive", "Limited free trial", "Learning curve"],
    features: [
      "Content generation",
      "SEO optimization",
      "Brand voice",
      "Templates",
    ],
    status: "active" as const,
    website: "https://jasper.ai",
    documentation: "https://jasper.ai/help",
  },
  {
    name: "Copy.ai",
    description: "AI copywriting tool for creating marketing content and copy",
    url: "https://copy.ai",
    category: "ai-business",
    subcategory: "Content Creation",
    tags: ["AI", "Copywriting", "Marketing", "Content", "Business"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://copy.ai/favicon.ico",
    color: "#8b5cf6",
    pros: ["Easy to use", "Templates", "Free tier", "Marketing focus"],
    cons: ["Limited features", "Quality varies", "Subscription required"],
    features: [
      "Copy generation",
      "Templates",
      "Brand voice",
      "Content optimization",
    ],
    status: "active" as const,
    website: "https://copy.ai",
    documentation: "https://copy.ai/help",
  },

  // Audio & Music
  {
    name: "Mubert",
    description: "AI music generation platform for creating original music",
    url: "https://mubert.com",
    category: "ai-audio",
    subcategory: "Music Generation",
    tags: ["AI", "Music", "Generation", "Creative", "Royalty-free"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://mubert.com/favicon.ico",
    color: "#ec4899",
    pros: [
      "Royalty-free music",
      "Easy to use",
      "Multiple genres",
      "API available",
    ],
    cons: ["Limited customization", "Quality varies", "Subscription required"],
    features: [
      "Music generation",
      "Genre selection",
      "Mood-based",
      "API access",
    ],
    status: "active" as const,
    website: "https://mubert.com",
    documentation: "https://mubert.com/api",
    apiAvailable: true,
    apiUrl: "https://mubert.com/api",
  },
  {
    name: "Descript",
    description: "AI-powered audio and video editing platform",
    url: "https://descript.com",
    category: "ai-audio",
    subcategory: "Audio Editing",
    tags: ["AI", "Audio", "Video", "Editing", "Podcasting"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://descript.com/favicon.ico",
    color: "#3b82f6",
    pros: [
      "Text-based editing",
      "AI voice cloning",
      "Easy to use",
      "Podcast focused",
    ],
    cons: ["Expensive", "Learning curve", "Limited free features"],
    features: [
      "Text-based editing",
      "Voice cloning",
      "Transcription",
      "Podcast tools",
    ],
    status: "active" as const,
    website: "https://descript.com",
    documentation: "https://help.descript.com",
  },

  // Beauty & Fashion
  {
    name: "YouCam Makeup",
    description: "AI-powered beauty and makeup try-on app by Perfect Corp",
    url: "https://youcam.com",
    category: "ai-beauty",
    subcategory: "Beauty & Fashion",
    tags: ["AI", "Beauty", "Makeup", "Virtual Try-On", "Mobile"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://youcam.com/favicon.ico",
    color: "#f472b6",
    pros: ["Realistic try-on", "Multiple brands", "Easy to use", "Mobile app"],
    cons: [
      "Limited features in free version",
      "Privacy concerns",
      "In-app purchases",
    ],
    features: [
      "Virtual makeup",
      "Hair color",
      "Skin analysis",
      "Product recommendations",
    ],
    status: "active" as const,
    website: "https://youcam.com",
    documentation: "https://youcam.com/support",
  },

  // Additional Tools
  {
    name: "ChatGPT Plus",
    description:
      "Advanced AI assistant with GPT-4, plugins, and advanced features",
    url: "https://chat.openai.com",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Chat", "GPT-4", "Plugins", "Advanced"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    color: "#10a37f",
    pros: [
      "GPT-4 access",
      "Plugins support",
      "Advanced features",
      "Priority access",
    ],
    cons: ["Monthly subscription", "Limited free tier", "Plugin costs"],
    features: [
      "GPT-4 model",
      "Plugin ecosystem",
      "Code interpreter",
      "Advanced analysis",
    ],
    status: "active" as const,
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
  },
  {
    name: "Firefly",
    description:
      "Adobe's AI-powered creative suite for image generation and editing",
    url: "https://firefly.adobe.com",
    category: "ai-image",
    subcategory: "Creative Suite",
    tags: ["AI", "Adobe", "Creative", "Design", "Professional"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Adobe_Systems_logo_and_wordmark.svg",
    color: "#ff0000",
    pros: [
      "Adobe integration",
      "Professional quality",
      "Commercial use",
      "Creative Cloud",
    ],
    cons: ["Adobe subscription", "Limited free credits", "Learning curve"],
    features: [
      "Text-to-image",
      "Vector graphics",
      "3D generation",
      "Brand-safe content",
    ],
    status: "active" as const,
    website: "https://adobe.com/firefly",
    documentation: "https://helpx.adobe.com/firefly/user-guide.html",
  },
  {
    name: "Synthesia STUDIO",
    description:
      "Professional AI video creation platform for businesses and creators",
    url: "https://synthesia.io/studio",
    category: "ai-video",
    subcategory: "Video Creation",
    tags: ["AI", "Video", "Business", "Professional", "Avatars"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://synthesia.io/favicon.ico",
    color: "#dc2626",
    pros: [
      "Professional avatars",
      "Business focus",
      "Custom branding",
      "High quality",
    ],
    cons: ["Expensive", "Enterprise pricing", "Limited customization"],
    features: [
      "AI avatars",
      "Custom branding",
      "Multi-language",
      "Professional templates",
    ],
    status: "active" as const,
    website: "https://synthesia.io",
    documentation: "https://help.synthesia.io",
  },
  {
    name: "Tabnine Pro",
    description:
      "Advanced AI code completion with team collaboration and security",
    url: "https://tabnine.com/pro",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "Team", "Security", "Enterprise"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://tabnine.com/favicon.ico",
    color: "#3b82f6",
    pros: [
      "Team features",
      "Security focus",
      "Custom training",
      "Enterprise support",
    ],
    cons: ["Expensive", "Complex setup", "Limited free features"],
    features: [
      "Team collaboration",
      "Custom models",
      "Security compliance",
      "API access",
    ],
    status: "active" as const,
    website: "https://tabnine.com",
    documentation: "https://tabnine.com/docs",
  },
  {
    name: "Writesonic",
    description:
      "AI-powered content creation platform for marketing and business",
    url: "https://writesonic.com",
    category: "ai-business",
    subcategory: "Content Creation",
    tags: ["AI", "Content", "Marketing", "SEO", "Business"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://writesonic.com/favicon.ico",
    color: "#8b5cf6",
    pros: ["SEO optimization", "Marketing focus", "Templates", "Free tier"],
    cons: ["Limited free credits", "Quality varies", "Subscription required"],
    features: [
      "SEO content",
      "Marketing copy",
      "Blog writing",
      "Product descriptions",
    ],
    status: "active" as const,
    website: "https://writesonic.com",
    documentation: "https://writesonic.com/help",
  },
  {
    name: "AIVA",
    description:
      "AI music composer for creating original compositions and soundtracks",
    url: "https://aiva.ai",
    category: "ai-audio",
    subcategory: "Music Composition",
    tags: ["AI", "Music", "Composition", "Soundtrack", "Creative"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://aiva.ai/favicon.ico",
    color: "#06b6d4",
    pros: [
      "Original compositions",
      "Multiple genres",
      "Commercial licensing",
      "Easy to use",
    ],
    cons: ["Limited customization", "Subscription required", "Quality varies"],
    features: [
      "Music composition",
      "Genre selection",
      "Commercial licensing",
      "API access",
    ],
    status: "active" as const,
    website: "https://aiva.ai",
    documentation: "https://aiva.ai/docs",
    apiAvailable: true,
    apiUrl: "https://aiva.ai/api",
  },
  {
    name: "Perfect Corp",
    description:
      "AI-powered beauty technology platform for virtual try-on and analysis",
    url: "https://perfectcorp.com",
    category: "ai-beauty",
    subcategory: "Beauty Technology",
    tags: ["AI", "Beauty", "Technology", "Virtual Try-On", "Analysis"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://perfectcorp.com/favicon.ico",
    color: "#ec4899",
    pros: [
      "Advanced technology",
      "Multiple applications",
      "Professional use",
      "High accuracy",
    ],
    cons: ["Expensive", "Enterprise focus", "Limited consumer access"],
    features: [
      "Virtual try-on",
      "Skin analysis",
      "Hair color",
      "Fashion recommendations",
    ],
    status: "active" as const,
    website: "https://perfectcorp.com",
    documentation: "https://perfectcorp.com/developers",
  },
  {
    name: "Coursera AI",
    description:
      "AI-powered learning platform with personalized education paths",
    url: "https://coursera.org",
    category: "ai-education",
    subcategory: "Online Learning",
    tags: ["AI", "Education", "Courses", "Certification", "University"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Coursera_logo.svg",
    color: "#0056d2",
    pros: [
      "University partnerships",
      "Certifications",
      "AI courses",
      "Flexible learning",
    ],
    cons: ["Expensive courses", "Time commitment", "Internet required"],
    features: [
      "AI-powered learning",
      "University courses",
      "Certifications",
      "Flexible schedule",
    ],
    status: "active" as const,
    website: "https://coursera.org",
    documentation: "https://coursera.org/help",
  },
  {
    name: "Babylon Health",
    description:
      "AI-powered healthcare platform for symptom checking and consultations",
    url: "https://babylonhealth.com",
    category: "ai-health",
    subcategory: "Healthcare",
    tags: [
      "AI",
      "Healthcare",
      "Telemedicine",
      "Symptom Checker",
      "Consultations",
    ],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://babylonhealth.com/favicon.ico",
    color: "#059669",
    pros: [
      "24/7 access",
      "AI diagnosis",
      "Telemedicine",
      "Professional doctors",
    ],
    cons: ["Limited coverage", "Subscription required", "Not emergency care"],
    features: [
      "Symptom checking",
      "AI diagnosis",
      "Video consultations",
      "Health monitoring",
    ],
    status: "active" as const,
    website: "https://babylonhealth.com",
    documentation: "https://babylonhealth.com/help",
  },
  {
    name: "DeepL",
    description:
      "AI-powered translation platform with superior accuracy and natural language",
    url: "https://deepl.com",
    category: "ai-business",
    subcategory: "Translation",
    tags: ["AI", "Translation", "Language", "Accuracy", "Professional"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://deepl.com/favicon.ico",
    color: "#0f172a",
    pros: [
      "Superior accuracy",
      "Natural language",
      "Professional use",
      "API available",
    ],
    cons: ["Limited free tier", "Expensive", "Fewer languages"],
    features: [
      "High-quality translation",
      "Natural language",
      "Document translation",
      "API access",
    ],
    status: "active" as const,
    website: "https://deepl.com",
    documentation: "https://deepl.com/docs-api",
    apiAvailable: true,
    apiUrl: "https://deepl.com/docs-api",
  },
  {
    name: "Lumen5",
    description:
      "AI video creation platform for social media and marketing content",
    url: "https://lumen5.com",
    category: "ai-video",
    subcategory: "Social Media",
    tags: ["AI", "Video", "Social Media", "Marketing", "Content"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://lumen5.com/favicon.ico",
    color: "#ef4444",
    pros: ["Social media focus", "Easy to use", "Templates", "Free tier"],
    cons: ["Limited customization", "Watermarks", "Subscription required"],
    features: [
      "Text-to-video",
      "Social media formats",
      "Templates",
      "Brand customization",
    ],
    status: "active" as const,
    website: "https://lumen5.com",
    documentation: "https://lumen5.com/help",
  },
  {
    name: "Beautiful.ai",
    description:
      "AI-powered presentation software for creating stunning slides",
    url: "https://beautiful.ai",
    category: "ai-business",
    subcategory: "Presentations",
    tags: ["AI", "Presentations", "Design", "Slides", "Business"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://beautiful.ai/favicon.ico",
    color: "#8b5cf6",
    pros: ["Beautiful designs", "AI assistance", "Templates", "Professional"],
    cons: ["Expensive", "Limited free trial", "Learning curve"],
    features: [
      "AI design suggestions",
      "Templates",
      "Real-time collaboration",
      "Brand customization",
    ],
    status: "active" as const,
    website: "https://beautiful.ai",
    documentation: "https://beautiful.ai/help",
  },
  {
    name: "Tome",
    description: "AI-powered storytelling and presentation platform",
    url: "https://tome.app",
    category: "ai-business",
    subcategory: "Presentations",
    tags: ["AI", "Storytelling", "Presentations", "Creative", "Narrative"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://tome.app/favicon.ico",
    color: "#6366f1",
    pros: ["Unique storytelling", "AI generation", "Easy to use", "Free tier"],
    cons: ["Limited templates", "New platform", "Subscription required"],
    features: [
      "AI story generation",
      "Interactive presentations",
      "Templates",
      "Collaboration",
    ],
    status: "active" as const,
    website: "https://tome.app",
    documentation: "https://tome.app/help",
  },
  {
    name: "Gamma",
    description: "AI-powered presentation and document creation platform",
    url: "https://gamma.app",
    category: "ai-business",
    subcategory: "Presentations",
    tags: ["AI", "Presentations", "Documents", "Design", "Productivity"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://gamma.app/favicon.ico",
    color: "#10b981",
    pros: ["AI generation", "Beautiful designs", "Easy to use", "Free tier"],
    cons: ["Limited customization", "New platform", "Subscription required"],
    features: [
      "AI content generation",
      "Design suggestions",
      "Templates",
      "Real-time collaboration",
    ],
    status: "active" as const,
    website: "https://gamma.app",
    documentation: "https://gamma.app/help",
  },
  {
    name: "Jasper Art",
    description:
      "AI image generation tool integrated with Jasper's content platform",
    url: "https://jasper.ai/art",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Marketing", "Business", "Jasper"],
    featured: true,
    pricing: "Paid" as const,
    logo: "https://jasper.ai/favicon.ico",
    color: "#10b981",
    pros: [
      "Marketing focus",
      "Jasper integration",
      "Easy to use",
      "Commercial use",
    ],
    cons: ["Expensive", "Limited features", "Subscription required"],
    features: [
      "Text-to-image",
      "Style presets",
      "Commercial licensing",
      "Jasper integration",
    ],
    status: "active" as const,
    website: "https://jasper.ai/art",
    documentation: "https://jasper.ai/help",
  },
  {
    name: "Leonardo.ai",
    description:
      "AI art generation platform for creating stunning digital artwork",
    url: "https://leonardo.ai",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Art", "Image Generation", "Creative", "Digital Art"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://leonardo.ai/favicon.ico",
    color: "#f59e0b",
    pros: ["High quality", "Artistic focus", "Free tier", "Community features"],
    cons: ["Limited free credits", "Watermarks", "Subscription required"],
    features: [
      "Text-to-image",
      "Style training",
      "Community gallery",
      "Commercial licensing",
    ],
    status: "active" as const,
    website: "https://leonardo.ai",
    documentation: "https://leonardo.ai/help",
  },
  {
    name: "Playground AI",
    description:
      "AI image generation platform with advanced customization options",
    url: "https://playgroundai.com",
    category: "ai-image",
    subcategory: "Image Generation",
    tags: ["AI", "Image Generation", "Customization", "Creative", "Advanced"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://playgroundai.com/favicon.ico",
    color: "#3b82f6",
    pros: [
      "Advanced controls",
      "Multiple models",
      "Free tier",
      "Custom training",
    ],
    cons: ["Complex interface", "Learning curve", "Limited free credits"],
    features: [
      "Multiple AI models",
      "Advanced controls",
      "Custom training",
      "Commercial licensing",
    ],
    status: "active" as const,
    website: "https://playgroundai.com",
    documentation: "https://playgroundai.com/docs",
  },
  {
    name: "ElevenLabs",
    description: "AI voice generation and text-to-speech platform",
    url: "https://elevenlabs.io",
    category: "ai-audio",
    subcategory: "Voice Generation",
    tags: ["AI", "Voice", "Text-to-Speech", "Voice Cloning", "Audio"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://elevenlabs.io/favicon.ico",
    color: "#8b5cf6",
    pros: [
      "High quality",
      "Voice cloning",
      "Multiple languages",
      "API available",
    ],
    cons: ["Expensive", "Limited free credits", "Privacy concerns"],
    features: [
      "Text-to-speech",
      "Voice cloning",
      "Multiple languages",
      "API access",
    ],
    status: "active" as const,
    website: "https://elevenlabs.io",
    documentation: "https://elevenlabs.io/docs",
    apiAvailable: true,
    apiUrl: "https://elevenlabs.io/docs",
  },
  {
    name: "Uberduck",
    description: "AI voice generation platform for creating custom voices",
    url: "https://uberduck.ai",
    category: "ai-audio",
    subcategory: "Voice Generation",
    tags: ["AI", "Voice", "Generation", "Custom", "Creative"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://uberduck.ai/favicon.ico",
    color: "#dc2626",
    pros: ["Custom voices", "Easy to use", "Free tier", "Community voices"],
    cons: ["Limited quality", "Privacy concerns", "Subscription required"],
    features: [
      "Voice cloning",
      "Text-to-speech",
      "Community voices",
      "API access",
    ],
    status: "active" as const,
    website: "https://uberduck.ai",
    documentation: "https://uberduck.ai/docs",
    apiAvailable: true,
    apiUrl: "https://uberduck.ai/docs",
  },
  {
    name: "CodeWhisperer",
    description: "Amazon's AI code generation and completion tool",
    url: "https://aws.amazon.com/codewhisperer",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "AWS", "Development", "IDE"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg",
    color: "#ff9900",
    pros: [
      "Free for individuals",
      "AWS integration",
      "Security focused",
      "IDE support",
    ],
    cons: ["AWS focused", "Limited languages", "Internet required"],
    features: [
      "Code completion",
      "Security scanning",
      "IDE integration",
      "AWS integration",
    ],
    status: "active" as const,
    website: "https://aws.amazon.com/codewhisperer",
    documentation: "https://docs.aws.amazon.com/codewhisperer",
  },
  {
    name: "Tabnine",
    description: "AI code completion tool for developers",
    url: "https://tabnine.com",
    category: "ai-code",
    subcategory: "Code Assistance",
    tags: ["AI", "Coding", "Completion", "IDE", "Development"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://tabnine.com/favicon.ico",
    color: "#3b82f6",
    pros: ["Fast completion", "Multiple languages", "IDE support", "Free tier"],
    cons: ["Limited features", "Privacy concerns", "Subscription required"],
    features: [
      "Code completion",
      "Multiple languages",
      "IDE integration",
      "Custom training",
    ],
    status: "active" as const,
    website: "https://tabnine.com",
    documentation: "https://tabnine.com/docs",
  },
  {
    name: "Hugging Face",
    description: "AI model hub and platform for machine learning models",
    url: "https://huggingface.co",
    category: "ai-code",
    subcategory: "Machine Learning",
    tags: ["AI", "Machine Learning", "Models", "Open Source", "Community"],
    featured: true,
    pricing: "Freemium" as const,
    logo: "https://huggingface.co/favicon.ico",
    color: "#fbbf24",
    pros: ["Huge model library", "Open source", "Community", "Free tier"],
    cons: ["Technical", "Learning curve", "Limited support"],
    features: ["Model hosting", "Inference API", "Training", "Community"],
    status: "active" as const,
    website: "https://huggingface.co",
    documentation: "https://huggingface.co/docs",
    apiAvailable: true,
    apiUrl: "https://huggingface.co/docs/api-inference",
  },
  {
    name: "TensorFlow",
    description: "Open-source machine learning framework by Google",
    url: "https://tensorflow.org",
    category: "ai-code",
    subcategory: "Machine Learning",
    tags: ["AI", "Machine Learning", "Framework", "Google", "Open Source"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg",
    color: "#ff6f00",
    pros: ["Open source", "Google backed", "Comprehensive", "Community"],
    cons: ["Complex", "Learning curve", "Hardware requirements"],
    features: [
      "Deep learning",
      "TensorFlow.js",
      "Model deployment",
      "Research tools",
    ],
    status: "active" as const,
    website: "https://tensorflow.org",
    documentation: "https://tensorflow.org/guide",
  },
  {
    name: "PyTorch",
    description: "Open-source machine learning framework by Meta",
    url: "https://pytorch.org",
    category: "ai-code",
    subcategory: "Machine Learning",
    tags: ["AI", "Machine Learning", "Framework", "Meta", "Open Source"],
    featured: true,
    pricing: "Free" as const,
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg",
    color: "#ee4c2c",
    pros: ["Open source", "Meta backed", "Python native", "Research focused"],
    cons: ["Complex", "Learning curve", "Hardware requirements"],
    features: [
      "Deep learning",
      "Research tools",
      "Model deployment",
      "Community",
    ],
    status: "active" as const,
    website: "https://pytorch.org",
    documentation: "https://pytorch.org/docs",
  },
];

export async function seedDatabase() {
  try {
    console.log("Starting database seeding...");

    // Create admin user
    const usersCollection = await getUsersCollection();
    const adminExists = await usersCollection.findOne({
      email: "heylelyaka@gmail.com",
    });

    if (!adminExists) {
      const hashedPassword = await bcrypt.hash("admin123", 12);
      const adminUser = createUser({
        email: "heylelyaka@gmail.com",
        name: "Heylel Yaka",
        password: hashedPassword,
        role: "admin",
      });

      await usersCollection.insertOne(adminUser);
      console.log("Admin user created");
    }

    // Seed tools
    const toolsCollection = await getToolsCollection();

    for (const toolData of initialTools) {
      const existingTool = await toolsCollection.findOne({
        name: toolData.name,
      });

      if (!existingTool) {
        const tool = createTool(toolData);
        await toolsCollection.insertOne(tool);
        console.log(`Tool "${toolData.name}" created`);
      }
    }

    console.log("Database seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}
