const { MongoClient } = require("mongodb");
const bcrypt = require("bcryptjs");

const MONGODB_URI =
  "mongodb+srv://heylelyaka:EHe7er5uIDlmz6jn@klicktools.r9d8lwn.mongodb.net/?retryWrites=true&w=majority&appName=klicktools";

// Comprehensive AI tools data
const initialTools = [
  // Chat & Language Models
  {
    name: "ChatGPT",
    description:
      "Advanced AI language model for conversation, writing, and content creation",
    url: "https://chat.openai.com",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Chat", "Writing", "OpenAI", "GPT-4"],
    featured: true,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    color: "#10a37f",
    pros: [
      "Powerful language model",
      "Great for writing",
      "Easy to use",
      "Regular updates",
    ],
    cons: ["Can be expensive", "Sometimes inaccurate", "Limited context"],
    features: [
      "Text generation",
      "Code assistance",
      "Translation",
      "Creative writing",
    ],
    status: "active",
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
    apiAvailable: true,
    apiUrl: "https://platform.openai.com/docs/api-reference",
    rating: 4.8,
    reviewCount: 1250,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Claude",
    description:
      "Anthropic's AI assistant for writing, analysis, and creative tasks",
    url: "https://claude.ai",
    category: "ai-chat",
    subcategory: "Language Models",
    tags: ["AI", "Writing", "Analysis", "Anthropic", "Claude"],
    featured: true,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/86/Anthropic_logo.svg",
    color: "#d97706",
    pros: ["Excellent writing", "Good reasoning", "Safe AI", "File uploads"],
    cons: ["Limited availability", "No mobile app", "Subscription required"],
    features: [
      "Text analysis",
      "File processing",
      "Creative writing",
      "Code assistance",
    ],
    status: "active",
    website: "https://anthropic.com",
    documentation: "https://docs.anthropic.com",
    rating: 4.7,
    reviewCount: 890,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // AI Writing Tools
  {
    name: "Jasper",
    description:
      "AI writing assistant for marketing, content, and creative writing",
    url: "https://jasper.ai",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Writing", "Marketing", "Content", "Copywriting"],
    featured: true,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Jasper_AI_logo.svg",
    color: "#ff6b35",
    pros: [
      "High-quality content",
      "Marketing focused",
      "Templates",
      "SEO optimized",
    ],
    cons: ["Expensive", "Limited free tier", "Requires editing"],
    features: [
      "Blog writing",
      "Marketing copy",
      "Email campaigns",
      "Social media",
    ],
    status: "active",
    website: "https://jasper.ai",
    documentation: "https://jasper.ai/help",
    apiAvailable: true,
    apiUrl: "https://jasper.ai/api",
    rating: 4.6,
    reviewCount: 650,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Copy.ai",
    description: "AI copywriting tool for marketing and business content",
    url: "https://copy.ai",
    category: "ai-writing",
    subcategory: "Copywriting",
    tags: ["AI", "Copywriting", "Marketing", "Business", "Content"],
    featured: true,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Copy.ai_logo.svg",
    color: "#6366f1",
    pros: ["Easy to use", "Marketing templates", "Free tier", "Quick results"],
    cons: ["Limited creativity", "Requires editing", "Repetitive content"],
    features: [
      "Ad copy",
      "Product descriptions",
      "Email marketing",
      "Social media",
    ],
    status: "active",
    website: "https://copy.ai",
    documentation: "https://copy.ai/help",
    apiAvailable: true,
    apiUrl: "https://copy.ai/api",
    rating: 4.5,
    reviewCount: 720,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Writesonic",
    description: "AI writing platform for blogs, ads, and business content",
    url: "https://writesonic.com",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Writing", "Blogging", "Marketing", "SEO"],
    featured: true,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Writesonic_logo.svg",
    color: "#8b5cf6",
    pros: ["SEO optimized", "Blog writing", "Multiple languages", "Templates"],
    cons: ["Limited free credits", "Quality varies", "Requires editing"],
    features: [
      "Blog articles",
      "Landing pages",
      "Product descriptions",
      "SEO content",
    ],
    status: "active",
    website: "https://writesonic.com",
    documentation: "https://writesonic.com/docs",
    apiAvailable: true,
    apiUrl: "https://writesonic.com/api",
    rating: 4.4,
    reviewCount: 1100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Grammarly",
    description: "AI-powered writing assistant for grammar, style, and tone",
    url: "https://grammarly.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Grammar", "Writing", "Editing", "Style"],
    featured: true,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Grammarly_logo.svg",
    color: "#15c39a",
    pros: [
      "Excellent grammar",
      "Style suggestions",
      "Browser integration",
      "Free tier",
    ],
    cons: ["Limited AI writing", "Premium expensive", "Privacy concerns"],
    features: [
      "Grammar checking",
      "Style suggestions",
      "Tone detection",
      "Plagiarism check",
    ],
    status: "active",
    website: "https://grammarly.com",
    documentation: "https://grammarly.com/help",
    apiAvailable: true,
    apiUrl: "https://grammarly.com/api",
    rating: 4.3,
    reviewCount: 950,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "ProWritingAid",
    description: "Comprehensive writing editor with AI-powered suggestions",
    url: "https://prowritingaid.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Writing", "Editing", "Grammar", "Style"],
    featured: false,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/ProWritingAid_logo.svg",
    color: "#dc2626",
    pros: [
      "Comprehensive editing",
      "Detailed reports",
      "Multiple integrations",
      "Academic focus",
    ],
    cons: ["Expensive", "Complex interface", "No free tier"],
    features: [
      "Grammar checking",
      "Style analysis",
      "Readability scores",
      "Writing reports",
    ],
    status: "active",
    website: "https://prowritingaid.com",
    documentation: "https://prowritingaid.com/help",
    apiAvailable: false,
    rating: 4.2,
    reviewCount: 450,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Hemingway Editor",
    description: "Writing app that makes your writing bold and clear",
    url: "https://hemingwayapp.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Writing", "Clarity", "Style", "Editing"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Hemingway_Editor_logo.svg",
    color: "#f59e0b",
    pros: [
      "Improves clarity",
      "Simple interface",
      "Free web version",
      "Readability focus",
    ],
    cons: ["Limited features", "No grammar check", "Basic AI"],
    features: [
      "Readability analysis",
      "Style suggestions",
      "Sentence structure",
      "Word choice",
    ],
    status: "active",
    website: "https://hemingwayapp.com",
    documentation: "https://hemingwayapp.com/help",
    apiAvailable: false,
    rating: 4.1,
    reviewCount: 320,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "QuillBot",
    description: "AI-powered paraphrasing and writing tool",
    url: "https://quillbot.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Paraphrasing", "Writing", "Grammar", "Translation"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/QuillBot_logo.svg",
    color: "#3b82f6",
    pros: [
      "Excellent paraphrasing",
      "Grammar checker",
      "Free tier",
      "Multiple languages",
    ],
    cons: ["Limited creativity", "Repetitive suggestions", "Premium expensive"],
    features: [
      "Paraphrasing",
      "Grammar checking",
      "Summarizer",
      "Citation generator",
    ],
    status: "active",
    website: "https://quillbot.com",
    documentation: "https://quillbot.com/help",
    apiAvailable: true,
    apiUrl: "https://quillbot.com/api",
    rating: 4.0,
    reviewCount: 280,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rytr",
    description: "AI writing assistant for content creation and copywriting",
    url: "https://rytr.me",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Writing", "Content", "Copywriting", "Marketing"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Rytr_logo.svg",
    color: "#10b981",
    pros: ["Affordable", "Multiple use cases", "SEO optimized", "Templates"],
    cons: ["Limited creativity", "Quality varies", "Basic interface"],
    features: [
      "Blog writing",
      "Marketing copy",
      "Email campaigns",
      "Social media",
    ],
    status: "active",
    website: "https://rytr.me",
    documentation: "https://rytr.me/help",
    apiAvailable: true,
    apiUrl: "https://rytr.me/api",
    rating: 3.9,
    reviewCount: 180,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "ContentBot",
    description: "AI content generator for blogs, articles, and marketing",
    url: "https://contentbot.ai",
    category: "ai-writing",
    subcategory: "Content Writing",
    tags: ["AI", "Content", "Blogging", "Marketing", "SEO"],
    featured: false,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/6d/ContentBot_logo.svg",
    color: "#7c3aed",
    pros: [
      "Long-form content",
      "SEO focused",
      "Research integration",
      "High quality",
    ],
    cons: ["Expensive", "No free tier", "Limited templates"],
    features: [
      "Blog articles",
      "Research papers",
      "SEO content",
      "Content planning",
    ],
    status: "active",
    website: "https://contentbot.ai",
    documentation: "https://contentbot.ai/docs",
    apiAvailable: true,
    apiUrl: "https://contentbot.ai/api",
    rating: 3.8,
    reviewCount: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Wordtune",
    description:
      "AI writing assistant that helps you express your ideas better",
    url: "https://wordtune.com",
    category: "ai-writing",
    subcategory: "Writing Assistant",
    tags: ["AI", "Writing", "Expression", "Style", "Clarity"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Wordtune_logo.svg",
    color: "#ef4444",
    pros: [
      "Improves expression",
      "Browser integration",
      "Free tier",
      "Multiple styles",
    ],
    cons: ["Limited features", "Requires context", "Premium expensive"],
    features: [
      "Sentence rewriting",
      "Tone adjustment",
      "Style suggestions",
      "Clarity improvement",
    ],
    status: "active",
    website: "https://wordtune.com",
    documentation: "https://wordtune.com/help",
    apiAvailable: true,
    apiUrl: "https://wordtune.com/api",
    rating: 3.7,
    reviewCount: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Additional AI Image Tools
  {
    name: "Midjourney",
    description: "AI-powered image generation from text descriptions",
    url: "https://midjourney.com",
    category: "ai-image",
    subcategory: "Art Generation",
    tags: ["AI", "Image", "Generation", "Art", "Creative"],
    featured: true,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png",
    color: "#ff6b6b",
    pros: ["High quality", "Creative", "Fast generation", "Community"],
    cons: ["Expensive", "Discord only", "No API", "Limited control"],
    features: [
      "Text to image",
      "Art generation",
      "Style variations",
      "Community gallery",
    ],
    status: "active",
    website: "https://midjourney.com",
    documentation: "https://midjourney.com/docs",
    apiAvailable: false,
    rating: 4.7,
    reviewCount: 890,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "DALL-E",
    description: "OpenAI's AI system for creating realistic images from text",
    url: "https://openai.com/dall-e-2",
    category: "ai-image",
    subcategory: "Art Generation",
    tags: ["AI", "Image", "Generation", "OpenAI", "Creative"],
    featured: true,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg",
    color: "#10a37f",
    pros: ["High quality", "Realistic", "Easy to use", "API available"],
    cons: ["Expensive", "Limited credits", "Content policy", "No free tier"],
    features: ["Text to image", "Image editing", "Variations", "API access"],
    status: "active",
    website: "https://openai.com/dall-e-2",
    documentation: "https://platform.openai.com/docs/guides/images",
    apiAvailable: true,
    apiUrl: "https://platform.openai.com/docs/api-reference/images",
    rating: 4.6,
    reviewCount: 750,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Stable Diffusion",
    description: "Open-source AI image generation model",
    url: "https://stability.ai",
    category: "ai-image",
    subcategory: "Art Generation",
    tags: ["AI", "Image", "Generation", "Open Source", "Creative"],
    featured: true,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/86/Stability_AI_logo.svg",
    color: "#6366f1",
    pros: ["Open source", "Free to use", "Customizable", "Community"],
    cons: ["Complex setup", "Hardware requirements", "Quality varies"],
    features: [
      "Text to image",
      "Image to image",
      "Custom models",
      "Local generation",
    ],
    status: "active",
    website: "https://stability.ai",
    documentation: "https://stability.ai/docs",
    apiAvailable: true,
    apiUrl: "https://platform.stability.ai/docs/api-reference",
    rating: 4.5,
    reviewCount: 680,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Additional AI Video Tools
  {
    name: "Runway ML",
    description: "AI-powered video editing and generation platform",
    url: "https://runwayml.com",
    category: "ai-video",
    subcategory: "Video Editing",
    tags: ["AI", "Video", "Editing", "Generation", "Creative"],
    featured: false,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Runway_ML_logo.svg",
    color: "#6366f1",
    pros: [
      "Professional tools",
      "High quality",
      "Multiple features",
      "Industry standard",
    ],
    cons: ["Expensive", "Complex", "Learning curve", "No free tier"],
    features: [
      "Video generation",
      "Motion tracking",
      "Green screen removal",
      "Text to video",
    ],
    status: "active",
    website: "https://runwayml.com",
    documentation: "https://runwayml.com/docs",
    apiAvailable: true,
    apiUrl: "https://runwayml.com/api",
    rating: 4.4,
    reviewCount: 420,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Synthesia",
    description: "AI video generation platform for creating talking avatars",
    url: "https://synthesia.io",
    category: "ai-video",
    subcategory: "Avatar Generation",
    tags: ["AI", "Video", "Avatars", "Talking", "Business"],
    featured: false,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Synthesia_logo.svg",
    color: "#dc2626",
    pros: [
      "Realistic avatars",
      "Multiple languages",
      "Business focused",
      "High quality",
    ],
    cons: ["Expensive", "Limited customization", "No free tier"],
    features: [
      "Talking avatars",
      "Multiple languages",
      "Custom avatars",
      "Video templates",
    ],
    status: "active",
    website: "https://synthesia.io",
    documentation: "https://synthesia.io/docs",
    apiAvailable: true,
    apiUrl: "https://synthesia.io/api",
    rating: 4.3,
    reviewCount: 380,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Additional AI Code Tools
  {
    name: "GitHub Copilot",
    description: "AI-powered code completion and pair programming",
    url: "https://github.com/features/copilot",
    category: "ai-code",
    subcategory: "Code Assistant",
    tags: ["AI", "Coding", "GitHub", "IDE", "Productivity"],
    featured: true,
    pricing: "Paid",
    logo: "https://github.githubassets.com/images/modules/copilot/cp-head-square.png",
    color: "#2ea44f",
    pros: [
      "Excellent code completion",
      "IDE integration",
      "Multiple languages",
      "GitHub integration",
    ],
    cons: [
      "Expensive",
      "Privacy concerns",
      "Sometimes inaccurate",
      "Limited free tier",
    ],
    features: [
      "Code completion",
      "Function generation",
      "Documentation",
      "Test generation",
    ],
    status: "active",
    website: "https://github.com/features/copilot",
    documentation: "https://docs.github.com/en/copilot",
    apiAvailable: false,
    rating: 4.5,
    reviewCount: 720,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Replit",
    description: "Online IDE with AI coding assistance and collaboration",
    url: "https://replit.com",
    category: "ai-code",
    subcategory: "Development Environment",
    tags: ["AI", "Coding", "IDE", "Collaboration", "Online"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Replit_logo.svg",
    color: "#f59e0b",
    pros: ["Online IDE", "AI assistance", "Collaboration", "Free tier"],
    cons: ["Limited resources", "Internet dependent", "Basic features"],
    features: [
      "Online coding",
      "AI assistance",
      "Real-time collaboration",
      "Deployment",
    ],
    status: "active",
    website: "https://replit.com",
    documentation: "https://replit.com/docs",
    apiAvailable: true,
    apiUrl: "https://replit.com/api",
    rating: 4.2,
    reviewCount: 340,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Additional AI Business Tools
  {
    name: "Jarvis",
    description: "AI assistant for business automation and productivity",
    url: "https://jarvis.ai",
    category: "ai-business",
    subcategory: "Business Automation",
    tags: ["AI", "Business", "Automation", "Productivity", "Assistant"],
    featured: false,
    pricing: "Paid",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Jarvis_AI_logo.svg",
    color: "#3b82f6",
    pros: ["Business focused", "Automation", "Integration", "Customizable"],
    cons: ["Expensive", "Complex setup", "No free tier"],
    features: [
      "Business automation",
      "Data analysis",
      "Report generation",
      "Integration",
    ],
    status: "active",
    website: "https://jarvis.ai",
    documentation: "https://jarvis.ai/docs",
    apiAvailable: true,
    apiUrl: "https://jarvis.ai/api",
    rating: 4.1,
    reviewCount: 280,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Otter.ai",
    description: "AI-powered meeting transcription and note-taking",
    url: "https://otter.ai",
    category: "ai-business",
    subcategory: "Transcription",
    tags: ["AI", "Transcription", "Meetings", "Notes", "Business"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Otter.ai_logo.svg",
    color: "#10b981",
    pros: [
      "Accurate transcription",
      "Meeting notes",
      "Speaker identification",
      "Free tier",
    ],
    cons: ["Limited free minutes", "Privacy concerns", "Requires good audio"],
    features: [
      "Meeting transcription",
      "Speaker identification",
      "Note taking",
      "Integration",
    ],
    status: "active",
    website: "https://otter.ai",
    documentation: "https://otter.ai/help",
    apiAvailable: true,
    apiUrl: "https://otter.ai/api",
    rating: 4.0,
    reviewCount: 220,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Additional AI Education Tools
  {
    name: "Duolingo",
    description: "AI-powered language learning platform",
    url: "https://duolingo.com",
    category: "ai-education",
    subcategory: "Language Learning",
    tags: ["AI", "Education", "Language", "Learning", "Gamification"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Duolingo_logo.svg",
    color: "#58cc02",
    pros: [
      "Gamified learning",
      "Multiple languages",
      "Free tier",
      "Mobile app",
    ],
    cons: ["Limited depth", "Repetitive", "Premium expensive"],
    features: [
      "Language learning",
      "Gamification",
      "Progress tracking",
      "Mobile app",
    ],
    status: "active",
    website: "https://duolingo.com",
    documentation: "https://duolingo.com/help",
    apiAvailable: false,
    rating: 4.3,
    reviewCount: 560,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Khan Academy",
    description: "AI-enhanced educational platform for various subjects",
    url: "https://khanacademy.org",
    category: "ai-education",
    subcategory: "General Education",
    tags: ["AI", "Education", "Learning", "Free", "Comprehensive"],
    featured: false,
    pricing: "Free",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Khan_Academy_logo.svg",
    color: "#14bf96",
    pros: [
      "Completely free",
      "Comprehensive",
      "Multiple subjects",
      "Adaptive learning",
    ],
    cons: ["Limited AI features", "Basic interface", "No certificates"],
    features: [
      "Multiple subjects",
      "Adaptive learning",
      "Progress tracking",
      "Practice exercises",
    ],
    status: "active",
    website: "https://khanacademy.org",
    documentation: "https://khanacademy.org/help",
    apiAvailable: false,
    rating: 4.4,
    reviewCount: 890,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Additional AI Health Tools
  {
    name: "Ada Health",
    description: "AI-powered health assessment and symptom checker",
    url: "https://ada.com",
    category: "ai-health",
    subcategory: "Health Assessment",
    tags: ["AI", "Health", "Assessment", "Symptoms", "Medical"],
    featured: false,
    pricing: "Free",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Ada_Health_logo.svg",
    color: "#3b82f6",
    pros: [
      "Free health assessment",
      "Comprehensive",
      "Medical database",
      "Easy to use",
    ],
    cons: [
      "Not a replacement for doctors",
      "Limited accuracy",
      "Privacy concerns",
    ],
    features: [
      "Symptom checker",
      "Health assessment",
      "Medical information",
      "Appointment booking",
    ],
    status: "active",
    website: "https://ada.com",
    documentation: "https://ada.com/help",
    apiAvailable: false,
    rating: 4.2,
    reviewCount: 340,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Woebot",
    description: "AI mental health chatbot for emotional support",
    url: "https://woebot.io",
    category: "ai-health",
    subcategory: "Mental Health",
    tags: ["AI", "Mental Health", "Chatbot", "Support", "Therapy"],
    featured: false,
    pricing: "Freemium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Woebot_logo.svg",
    color: "#8b5cf6",
    pros: [
      "Mental health support",
      "24/7 availability",
      "Evidence-based",
      "Free tier",
    ],
    cons: [
      "Not a replacement for therapy",
      "Limited personalization",
      "Privacy concerns",
    ],
    features: [
      "Mental health support",
      "Mood tracking",
      "CBT techniques",
      "Daily check-ins",
    ],
    status: "active",
    website: "https://woebot.io",
    documentation: "https://woebot.io/help",
    apiAvailable: false,
    rating: 4.1,
    reviewCount: 280,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function seedDatabase() {
  const client = new MongoClient(MONGODB_URI);

  try {
    console.log("Connecting to MongoDB...");
    await client.connect();
    console.log("✅ Connected to MongoDB successfully!");

    const db = client.db();
    const toolsCollection = db.collection("tools");
    const usersCollection = db.collection("users");

    // Clear existing tools
    console.log("🗑️  Clearing existing tools...");
    await toolsCollection.deleteMany({});
    console.log("✅ Cleared existing tools");

    // Create admin user if it doesn't exist
    const adminExists = await usersCollection.findOne({
      email: "heylelyaka@gmail.com",
    });

    if (!adminExists) {
      const hashedPassword = await bcrypt.hash("admin123", 12);
      await usersCollection.insertOne({
        email: "heylelyaka@gmail.com",
        name: "Heylel Yaka",
        password: hashedPassword,
        role: "admin",
        favorites: [],
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      console.log("✅ Admin user created");
    }

    // Insert tools
    console.log("📝 Inserting tools...");
    const result = await toolsCollection.insertMany(initialTools);
    console.log(`✅ Inserted ${result.insertedCount} tools successfully!`);

    // Create indexes
    console.log("🔍 Creating database indexes...");
    await toolsCollection.createIndex({ name: 1 });
    await toolsCollection.createIndex({ category: 1 });
    await toolsCollection.createIndex({ featured: 1 });
    await toolsCollection.createIndex({ tags: 1 });
    await usersCollection.createIndex({ email: 1 }, { unique: true });
    console.log("✅ Created database indexes");

    console.log("🎉 Database seeding completed successfully!");
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    throw error;
  } finally {
    await client.close();
  }
}

// Run the seeding function
seedDatabase()
  .then(() => {
    console.log("✅ Seeding completed!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  });
